import { pt, type Dictionary } from "./pt";

export const en: Dictionary = {
  ...pt,
  locale: "en-GB",
  brand: {
    ...pt.brand,
    tagline: "handmade, with love ♡",
    description: "portuguese natural hygiene and beauty brand, handmade at home in small batches.",
  },
  nav: {
    home: "home", products: "products", ingredients: "ingredients", about: "about us", feedback: "feedback",
    cart: "cart", openMenu: "open menu", closeMenu: "close menu", skipToContent: "skip to content", homeLink: "lucrescente, home page",
  },
  productInfo: {
    notAntiperspirant: "not an antiperspirant",
    aluminiumFree: "aluminium free",
    alcoholFree: "alcohol free",
    customisable: "customisable",
    waterSavingLabel: "less water",
    waterSavingText:
      "we use no water to make this product. solid products leave far less residue and rinse out of hair and skin more easily, so you do not need to use as much water to feel clean, and because they need no packaging, we also save the water used to make plastic.",
    paperWrappedText:
      "we wrap every product in reused paper, because we put sustainability and mindful making ahead of needless consumption.",
    skinSafeLabel: "safe for skin",
    skinSafeText:
      "our solid shampoos can be used on the body too, with no worries: thanks to their natural ingredients and the absence of harsh chemicals, you can enjoy a multi-purpose shampoo every day!",
    contactTitle: "talk to us about this product",
    contactSuccess: "✓ message sent! thank you for getting in touch.",
    contactError: "we could not send your message. please try again, or email us directly at",
    contactName: "name",
    contactNamePlaceholder: "what is your name?",
    contactEmail: "email",
    contactEmailPlaceholder: "your email",
    contactMessage: "message",
    contactMessagePlaceholder: "tell us what you think, any questions, special requests...",
    contactSend: "send",
    contactSending: "sending...",
  },
  home: {
    ...pt.home,
    heroLabel: "handmade, with care",
    heroTitle: "simple care,\nmade with love and with\ningredients we trust.",
    heroPrimary: "see all products", heroSecondary: "see all ingredients", featuredTitle: "our current favourites", cardLink: "take a look →",
    productsTitle: "care for your days", productsSubtitle: "balms, shampoos, decorated candles and much more, handmade with carefully chosen ingredients.", productsButton: "see all products", featuredMoreLink: "see more",
    valuesTitle: "what guides us", valuesSubtitle: "thoughtfully chosen ingredients, less waste and room for everyone to care in their own way.", values: ["handmade", "honest ingredients", "less waste"],
    storyTitle: "a small brand, made with intention", storyText: "lucrescente started as a completely family project (long before it was even a project) and grew, little by little, to reach more people. we know our ingredients, tell each one's story, and still make everything in small batches, with the same care as day one.", storyLink: "discover our story →",
    ingredientsTitle: "the ingredients we use, one by one", ingredientsSubtitle: "each one has its own story and purpose. choose one to discover where it comes from and what it does.", ingredientsLink: "see all ingredients",
    contactTitle: "order your products", contactText: "for questions, customisations or special orders, get in touch.",
    contactButtons: { call: "call", sms: "text message", whatsapp: "whatsapp message", email: "email" }, categoryGroupHigiene: "hygiene", categoryGroupBeleza: "beauty", categoryGroupBemEstar: "wellness",
    shortAbout: "handmade hygiene, beauty and wellness products, made by mother and daughter, for healthier, more personal self-care.",
    testimonialsLabel: "who's already tried it",
    testimonialsTitle: "your comments",
    testimonialsSubtitle: "received in our inbox over the years, written by you.",
    testimonialsPrev: "previous feedback",
    testimonialsNext: "next feedback",
    showMore: "show more",
    showLess: "show less",
  },
  footer: { line: "lucrescente ☾ handmade, with love", contactsTitle: "contact", pagesTitle: "pages", shipping: "national and international shipping by order. larger quantities available by request.", returnsSummary: "wrong product, or damaged? you have 14 days to tell us, and the cost of sending it back is ours.", returnsLink: "read the returns policy →" },
  products: {
    ...pt.products, scrollLeft: "see previous categories", scrollRight: "see next categories", deodorantFact: "apply a thin layer to clean, dry skin: it spreads better with your body heat.", solidNote: "a solid product, with no water in the formula. keep it somewhere dry between uses so it lasts longer.", label: "handmade, one by one", title: "our products", allCategories: "all", filterLabel: "categories", whyItWorks: "why it works", candleCaseLabel: "why they work", candleCase: "paraffin is a leftover of refining crude oil which, as it burns, releases soot and toxic compounds that stay in the air and harm our lungs. soy wax candles burn more slowly and evenly (without tunnelling) and never reach temperatures as high as paraffin ones. they also release no soot, and contain no toxic or synthetic component of any kind! the scent comes from essential oils and never from synthetic fragrances, and the decoration is natural: dried flowers and leaves, shells and small stones.", candleOrder: "just send us a message to order!", flavourLabel: "essential oil", flavourNone: "no oil", flavourHint: "sweet orange: a sweet, citrusy scent. peppermint: a cool, fresh feel on the lips.", hairTypeNote: "what hair type this is for", recommendedFor: "recommended for", notRecommendedFor: "not recommended for", mainIngredients: "main ingredients", allergenNoteLabel: "please note",
    noIngredientsListed: "this product's ingredient list has not been published yet. get in touch to find out more.", noCopy: "this product's story is still being written at home.", noPhoto: "no photograph yet", galleryPrevious: "previous image", galleryNext: "next image", galleryOf: (name: string) => `photographs of ${name}`, price: "price", onRequest: "made to order", talkToUs: "order →",
    soldOutTag: "sold out", priceFrom: "from ", addToCart: "add to cart", added: "added to cart", quantity: "quantity", variant: "size",
    stockLeft: (n: number) => (n === 1 ? "only 1 left" : `${n} left`), orderMessage: (name: string) => `hi! i'd like to order: ${name}`,
    backToCatalog: "← back to products", relatedTitle: "build your set", relatedPrev: "previous products", relatedNext: "next products", usedInTitle: "where we use this ingredient", emptyCategory: "there are no products in this category yet. get in touch to hear what is coming.", organicNote: "* organic ingredient", scentLabel: "scent", scentHint: "choose up to 2 essential oils.", scentCombosLabel: "the most popular choices", scentMaxReached: "you have picked 2 oils: remove one to swap.", scentHarsh: "cinnamon is one of the harshest essential oils on skin. if you choose it, don't use the melted wax for massage or directly on the skin.",
  },
  ingredients: {
    ...pt.ingredients, label: "plant and mineral origin", title: "the ingredients we use, one by one", subtitle: "each one has its own story and purpose. choose one to discover where it comes from and what it does", allCategories: "all",
    sections: { scientificName: "scientific name", origin: "origin", properties: "properties", applications: "applications at lucrescente" }, backToIndex: "← back to ingredients", productsUsing: "products with this ingredient", noProducts: "we have not linked this ingredient to a catalogue product yet.", searchPlaceholder: "search for an ingredient", noResults: "we could not find an ingredient with that name.",  },
  about: {
    ...pt.about, label: "our story", title: "two ways of looking at care", intro: "lucrescente was born from the meeting of scientific knowledge about plants and a sensitive, creative way of looking at everyday life.",
    values: ["family-owned business", "ecological and sustainable", "safe for children and sensitive skin", "no endocrine disruptors", "accessible prices for everyone"],
    lucieName: "lucie", lucieText: "i hold a phd in biosciences, in agroecology: the last few years were spent immersed in sunflowers, pollinators and nature conservation. that same attentive, rigorous and curious perspective guides the choice of ingredients and the creation of every lucrescente recipe.", luanaName: "luana", luanaText: "i am in the third year of my fine arts degree and bring aesthetic care, creativity and sensitivity to the brand. i think about how each product is presented, described and woven into small everyday care rituals.", close: "between us, science meets expression and every product gains its own story.", backLink: "back to the home page",
  },
  returns: { ...pt.returns, label: "returns", title: "if something arrives wrong", intro: "everything is made by hand and wrapped with care, but the journey to you does not always go well. if it goes wrong, we will sort it out.", contactTitle: "get in touch", groups: [
    { title: "when we accept a return", text: "we accept returns if you receive the wrong product, or the right one damaged: a broken jar, a dirty container, or a product that has melted or shattered. it makes no difference whether you have opened it or it is still sealed: what we need is proof that it is not right." },
    { title: "how long you have", text: "once the product reaches you, you have 14 days to ask for a return." },
    { title: "how to ask", text: "get in touch by any of the ways listed on the site: whatsapp, message, phone call or email. all we ask for is proof: a photograph of the product as it arrived, or of the wrong product you received." },
    { title: "who pays for the return", text: "we do. if the return is accepted, the cost of sending it back is ours." },
  ] },
  faq: { ...pt.faq, label: "frequently asked questions", title: "what people ask us most", intro: "the questions that reach us most often by message, gathered here. if yours is not below, write to us: we always reply.", stillAsking: "still have a question that is not here?", contactLink: "get in touch →", groups: [
    { title: "the products", items: [
      { q: "which solid shampoo is for me?", a: "we have four: for oily, dry and normal hair, and a neutral one that is also fine for children. the dry-hair one is the one people with a sensitive scalp ask us for most, and the neutral one is what we recommend for ultra-sensitive skin and scalps, since it has no essential oils in the formula. not sure? tell us about your hair and we will help you choose!" },
      { q: "can i use a solid shampoo if i dye or straighten my hair?", a: "you can! all our solid shampoos get along well with coloured hair and with straightened hair. we don't recommend them on bleached hair, because they have no anti-yellowing effect." },
      { q: "how should i store solid products?", a: "somewhere dry between uses. they have no water in the formula, and keeping them away from water when you aren't using them is what makes them last longest." },
      { q: "are your deodorants antiperspirants?", a: "no, and we make a point of saying so. they contain no aluminium and no alcohol, so they don't block perspiration or clog the pores: they gently control bacteria and odour, and let the skin do what it already knows how to do." },
      { q: "i have sensitive skin. is there anything i should watch for?", a: "several products contain essential oils, which can irritate or cause an allergic reaction on more sensitive skin, and the deodorants contain baking soda, which on some skin irritates the underarms, especially after a recent shave. we flag this on each product, under the ingredients. if in doubt, try a small patch first and talk to us: we can adapt the formula." },
      { q: "which products can i use directly on my skin?", a: "nearly all of them: the candles (except the coloured ones, which carry pigment), the shampoos, the air fresheners, the lipsticks, the deodorants, the roll-ons, the soaps and the relaxing spray. the solid shampoos double as a soap, since they contain no harsh chemicals (the dry-hair one has been used by people with atopic skin), and the soy wax in the candles is moisturising, so it can go on skin too. we choose the ingredients with this in mind, but your skin is yours and you know it best: if it is sensitive, try a small patch first." },
    ] },
    { title: "orders and shipping", items: [
      { q: "do you ship outside Portugal?", a: "we do! we ship all over the country and abroad. the cost depends on the destination, and you see the right amount at the end of checkout, before you confirm." },
      { q: "the product i want is sold out. can i still order it?", a: "you can, yes. we make everything by hand in small batches, and some products (the shampoos, the conditioners and the soaps) need time to rest and mature before they can be sent. if one sells out, we take the order and let you know as soon as it is ready. and if you need a bigger amount, we can make that too!" },
      { q: "can i ask for something made specifically for me?", a: "of course! we adapt a formula to what you need: gentler, stronger, or with a different scent. tell us what you have in mind before ordering and we will think it through with you." },
      { q: "can i return a product?", a: "of course. if the wrong product reaches you, or the right one but spoiled (a broken jar, a dirty container, a product that has melted or shattered), tell us: it makes no difference whether you have opened it, we just need a photo to understand what happened. you have 14 days after receiving it, and the cost of sending it back is ours. the returns page explains it all." },
    ] },
    { title: "sustainability", items: [
      { q: "why are the products solid?", a: "because at home we use no water in making them, and a solid product needs no packaging (which also saves the water that making that plastic would have taken). day to day they leave less residue and rinse more easily from hair and skin, so you use less water too. and they travel far better: no packaging, and no cabin liquid limits." },
      { q: "what are your candles made of?", a: "soy wax, which is plant-based. it burns more slowly and evenly (without tunnelling) and never reaches temperatures as high as the paraffin in supermarket candles, so it lasts longer with no wax wasted. it releases no soot and contains no toxic or synthetic component of any kind. the scent comes from essential oils and never from synthetic fragrances, and the decoration is natural: dried flowers and leaves, shells and small stones, many of them pressed and prepared by us." },
    ] },
  ] },
  cart: { ...pt.cart, title: "your cart", empty: "your cart is empty for now.", emptyHint: "take a look at our products and choose at your own pace.", browse: "see products", subtotal: "subtotal", shippingNote: "shipping is calculated at the next step, according to the destination.", checkout: "place order", checkingOut: "preparing payment…", remove: "remove", increase: "one more", decrease: "one less", close: "close", continue: "continue browsing", viewCart: "view cart", cancelled: "payment was not completed. your cart is still here whenever you are ready.", stockAdjusted: (name: string, n: number) => n === 0 ? `${name} sold out and was removed from your cart.` : `we can only send ${n} of ${name} for now; the quantity was adjusted.`, maxReached: "there are no more units available right now.", secure: "secure payment through Stripe", itemsCount: (n: number) => n === 1 ? "1 item" : `${n} items`, errorTitle: "we could not continue", errorGeneric: "something went wrong while preparing payment. try again shortly or get in touch.", ok: "ok" },
  checkout: { ...pt.checkout, title: "confirm order", summary: "order summary", shippingTo: "shipping to",  paymentMethod: "payment method",  paymentNote: "you can pay by card, MB WAY or apple pay: you choose on the next step, on Stripe's secure page.",     continuePayment: "continue to payment", subtotal: "subtotal", shipping: "shipping", total: "total", backToCart: "back to cart" },
  order: { ...pt.order, title: "thank you. we received your order.", message: "we prepare every order with care", detail: "we will prepare everything at home and send it as soon as it is ready. if you have any questions, get in touch.", summary: "order summary", reference: "reference", shippingTo: "shipping to", shipping: "shipping", total: "total", notFound: "we could not find this order. if you have just paid, wait a moment and refresh the page.", processing: "we are confirming your payment. this may take a few seconds.", backHome: "back to the home page", emailNote: (email: string) => `we have your contact: ${email}. we will be in touch there about your order.` },
  errors: { notFoundTitle: "we could not find this page.", notFoundText: "it may have moved. take a look at our products or ingredients.", genericTitle: "something went wrong.", genericText: "try again shortly. if it continues, get in touch.", retry: "try again" },
  contact: { title: "get in touch", call: "call", sms: "text", whatsapp: "whatsapp", email: "email", otherMethods: "other ways to reach us" },
};
