import { pt, type Dictionary } from "./pt";

export const en: Dictionary = {
  ...pt,
  locale: "en-GB",
  brand: {
    ...pt.brand,
    tagline: "handmade, with love 🌱",
    description: "portuguese natural hygiene and beauty brand, handmade at home in small batches.",
  },
  nav: {
    home: "home", products: "products", ingredients: "ingredients", about: "about us", care: "care & sustainability", fairs: "fairs and markets", feedback: "feedback",
    cart: "cart", openMenu: "open menu", closeMenu: "close menu", skipToContent: "skip to content", homeLink: "lucrescente, home page",
  },
  fairs: {
    title: "fairs and markets",
    intro:
      "besides the online shop, you can also find us at local fairs and markets — showing the products in person, meeting the people who'll use them, and sometimes making custom pieces on the spot. follow our instagram to find out where we'll be next.",
    comingSoon: "more information about the next events and fairs where you can find us is coming soon!",
    metaDescription: "find us at local fairs and markets",
  },
  productInfo: {
    notAntiperspirant: "not an antiperspirant",
    aluminiumFree: "aluminium free",
    alcoholFree: "alcohol free",
    customisable: "customisable",
    waterSavingLabel: "less water",
    waterSavingText:
      "we use no water to make this product. solid products leave far less residue and rinse out of hair and skin more easily, so you do not need to use as much water to feel clean — and because they need no packaging, we also save the water used to make plastic.",
    reusableLabel: "reusable",
    reusableText:
      "all our packaging is reusable. if you have an old container of ours or from another brand, bring it to us and get our reuse discount on your next order!",
    paperWrappedText:
      "we wrap every product in reused paper, because we put sustainability and mindful making ahead of needless consumption.",
    skinSafeLabel: "safe for skin",
    skinSafeText:
      "our solid shampoos can be used on the body too, with no worries: thanks to their natural ingredients and the absence of harsh chemicals, you can enjoy a multi-purpose shampoo every day!",
    contactTitle: "talk to us about this product",
    contactSuccess: "✓ message sent! thank you for getting in touch.",
    contactError: "we could not send your message. please try again, or email us directly at",
    contactName: "name",
    contactNamePlaceholder: "what is your name?",
    contactEmail: "email",
    contactEmailPlaceholder: "your email",
    contactMessage: "message",
    contactMessagePlaceholder: "tell us what you think, any questions, special requests...",
    contactSend: "send",
    contactSending: "sending...",
  },
  home: {
    ...pt.home,
    heroLabel: "handmade, with care",
    heroTitle: "simple care, made with love and ingredients we trust.",
    heroSubtitle: "at home, every product begins with an ingredient we know well — and we love sharing its story with you before it reaches your skin.",
    heroPrimary: "see all products", heroSecondary: "see all ingredients", featuredTitle: "our current favourites", cardLink: "take a look →",
    productsTitle: "care for your days", productsSubtitle: "balms, shampoos, decorated candles and much more, handmade with carefully chosen ingredients.", productsButton: "see all products", featuredMoreLink: "see more",
    valuesTitle: "what guides us", valuesSubtitle: "thoughtfully chosen ingredients, less waste and room for everyone to care in their own way.", values: ["handmade", "honest ingredients", "less waste"],
    storyTitle: "a small brand, made with intention", storyText: "lucrescente started as a completely family project — long before it was even a project — and grew, little by little, to reach more people. we know our ingredients, tell each one's story, and still make everything in small batches, with the same care as day one.", storyLink: "discover our story →",
    ingredientsTitle: "the ingredients we use, one by one", ingredientsSubtitle: "each one has its own story and purpose. choose one to discover where it comes from and what it does 🌿", ingredientsLink: "see all ingredients →",
    contactTitle: "order your products", contactText: "for questions, customisations or special orders, get in touch.",
    contactButtons: { call: "call", sms: "text message", whatsapp: "whatsapp message", email: "email" }, candleCitronelaName: "citronella", candleFlowers: "dried flowers", candleMessage: "with personalised messages", candleMassage: "massage", candleAltCitronela1: "three citronella candles in glass jars with a black label, on pink and blue floral fabric", candleAltCitronela2: "three candles in glass jars with a black label next to dried flowers", candleAltMassagem: "a wicker basket with a candle in a metal tin, a candle in a glass jar with a red ribbon, a jar of bath salts and a roll-on, on a christmas cloth with lights", categoryGroupHigiene: "hygiene", categoryGroupBeleza: "beauty", categoryGroupBemEstar: "wellness",
    shortAbout: "handmade hygiene, beauty and wellness products, made by mother and daughter, for healthier, more personal self-care.",
    testimonialsLabel: "who's already tried it",
    testimonialsTitle: "your comments",
    testimonialsSubtitle: "received in our inbox over the years, written by you.",
    testimonialsPrev: "previous feedback",
    testimonialsNext: "next feedback",
    showMore: "show more",
    showLess: "show less",
  },
  footer: { line: "lucrescente — handmade, with love 🌱", contactsTitle: "contact", pagesTitle: "pages", shipping: "national and international shipping by order. larger quantities available by request." },
  products: {
    ...pt.products, scrollLeft: "see previous categories", scrollRight: "see next categories", deodorantFact: "apply a thin layer to clean, dry skin — it spreads better with your body heat.", solidNote: "a solid product, with no water in the formula. keep it somewhere dry between uses so it lasts longer.", label: "handmade, one by one", title: "our products", allCategories: "all", filterLabel: "categories", whyItWorks: "why it works", hairTypeNote: "what hair type this is for", recommendedFor: "recommended for", notRecommendedFor: "not recommended for", mainIngredients: "main ingredients", allergenNoteLabel: "please note",
    noIngredientsListed: "this product's ingredient list has not been published yet. get in touch to find out more.", noCopy: "this product's story is still being written at home.", noPhoto: "no photograph yet", galleryPrevious: "previous image", galleryNext: "next image", galleryOf: (name: string) => `photographs of ${name}`, price: "price", onRequest: "made to order", talkToUs: "get in touch →",
    soldOut: "currently sold out. get in touch to place an order", soldOutShort: "currently sold out", priceFrom: "from ", addToCart: "add to cart", added: "added to cart", quantity: "quantity", variant: "size",
    stockLeft: (n: number) => (n === 1 ? "only 1 left" : `${n} left`), orderMessage: (name: string) => `hi! i'd like to order: ${name}`,
    ownContainerLabel: "own container", candleNote: "if you prefer, we can make your candles in your own jars, mugs or bowls — just bring us the containers.",
    backToCatalog: "← back to products", relatedTitle: "build your set", relatedPrev: "previous products", relatedNext: "next products", usedInTitle: "where we use this ingredient", emptyCategory: "there are no products in this category yet. get in touch to hear what is coming.", organicNote: "* organic ingredient",
  },
  ingredients: {
    ...pt.ingredients, label: "plant and mineral origin", title: "the ingredients we use, one by one", subtitle: "each one has its own story and purpose. choose one to discover where it comes from and what it does 🌿", allCategories: "all",
    sections: { scientificName: "scientific name", origin: "origin", properties: "properties", applications: "applications at lucrescente" }, backToIndex: "← back to ingredients", productsUsing: "products with this ingredient", noProducts: "we have not linked this ingredient to a catalogue product yet.", searchPlaceholder: "search for an ingredient", noResults: "we could not find an ingredient with that name.",  },
  about: {
    ...pt.about, label: "our story", title: "two ways of looking at care", intro: "lucrescente was born from the meeting of scientific knowledge about plants and a sensitive, creative way of looking at everyday life.",
    promise: "lucrescente is a family-owned, ecological and sustainable business, mindful and safe for children and sensitive skin. it contains no endocrine disruptors. we keep our prices accessible because access to hygiene and beauty products should be available to everyone.", values: ["family-owned business", "ecological and sustainable", "safe for children and sensitive skin", "no endocrine disruptors", "accessible prices for everyone"],
    lucieName: "lucie", lucieText: "i hold a phd in biosciences, in agroecology — the last few years were spent immersed in sunflowers, pollinators and nature conservation. that same attentive, rigorous and curious perspective guides the choice of ingredients and the creation of every lucrescente recipe.", luanaName: "luana", luanaText: "i am in the third year of my fine arts degree and bring aesthetic care, creativity and sensitivity to the brand. i think about how each product is presented, described and woven into small everyday care rituals.", close: "between us, science meets expression and every product gains its own story.", backLink: "back to the home page",
  },
  care: { ...pt.care, label: "care & sustainability", title: "because every small choice matters", intro: "beyond the ingredients, every lucrescente product carries a way of thinking — more natural, slower and with less waste. here is why.", chapters: [
    { slug: "poupamos-agua", title: "we save water", text: "our shampoos, conditioners and soaps are solid — we use no water in their manufacture. in your daily routine, solid products leave much less residue and rinse more easily from hair and skin, so you do not need to use as much water. because solid products use no packaging, we also save the water used to make plastic." },
    { slug: "embalagens", title: "reused packaging and wrapping", text: "all our packaging is reusable. if you have an old container, bring it to us and we will reuse it for your next product with a reuse discount. our wrapping is sewn by hand from reused fabrics — even the thread is made from cotton and other recycled fibres. more reuse, less waste." },
    { slug: "velas", title: "our candles", text: "lucrescente candles are made with vegetable soy wax, which melts slowly and evenly — so they last longer, without wasted wax, and contain no petroleum derivatives or synthetic fragrances. most of the decorative elements we use are natural: dried flowers and leaves, shells, small stones... some plant elements are even pressed and prepared by us. we can also make candles in your own jars, mugs or bowls." },
    { slug: "feito-a-mao", title: "handmade, in small batches", text: "lucrescente products are made entirely from natural ingredients, by hand and in small quantities at a time — to ensure the quality of our raw materials and the care taken in making them. some products can be replenished daily; others, such as shampoos, conditioners and soaps, need more rest and maturation. if a slower product sells out, we accept orders and ship nationally and internationally." },
    { slug: "desodorizantes", title: "our deodorants", text: "our deodorants are not antiperspirants and contain no aluminium or alcohol. choosing a healthy deodorant for our skin is important — applied so close to the body, it should not block perspiration or clog pores. we prefer to respect the skin's natural function, gently controlling bacteria and odour." },
    { slug: "dicas", title: "tips for use", text: "our solid shampoos can also be used on the body. because they contain natural ingredients and no harsh chemicals, some can even help calm skin problems such as atopic skin. our soy wax is moisturising and can be applied directly to the skin. solid toiletries are also practical for travel, without liquid limits." },
    { slug: "biologicos", title: "organic ingredients", text: "whenever possible, we choose organic ingredients — marked with * in product descriptions so you have better information about what you are using." },
    { slug: "feiras-e-mercados", title: "fairs and markets", text: "besides the online shop, you can also find us at local fairs and markets — showing the products in person, meeting the people who'll use them, and sometimes making custom pieces on the spot. follow our instagram to find out where we'll be next." },
  ] },
  faq: { ...pt.faq, label: "frequently asked questions", title: "what people ask us most", intro: "the questions that reach us most often by message, gathered here. if yours is not below, write to us — we always reply.", stillAsking: "still have a question that is not here?", contactLink: "get in touch →", groups: [
    { title: "the products", items: [
      { q: "which solid shampoo is for me?", a: "there are four: for oily hair, for dry hair, for normal hair, and a gentle one for children. the dry-hair bar is the one most sought out by people with a sensitive scalp, and the gentle one is what we recommend for ultra-sensitive skin and scalps, since it has no oils in the formula. if you are unsure, tell us about your hair and we will help you choose." },
      { q: "can i use a solid shampoo if i dye or straighten my hair?", a: "yes — all our solid shampoos can be used on dyed hair and on relaxed or straightened hair. we do not recommend them on bleached hair, because they have no anti-yellowing (purple-toning) effect." },
      { q: "can a solid shampoo be used as a soap?", a: "it can. because they contain no harsh chemicals, our solid shampoos can be used on the body — the dry-hair one in particular has been used by people with atopic skin." },
      { q: "how should i store solid products?", a: "somewhere dry between uses. solid products have no water in the formula, and keeping them out of the water when they are not in use is what makes them last longest." },
      { q: "are your deodorants antiperspirants?", a: "no. they contain no aluminium and no alcohol, and they neither block perspiration nor clog the pores — they control bacteria and odour gently, respecting how the skin naturally works." },
      { q: "i have sensitive skin. is there anything i should watch for?", a: "several products contain essential oils, which can cause irritation or an allergic reaction on more sensitive skin; the deodorants contain sodium bicarbonate, which on some skin irritates the underarms, especially shortly after hair removal. we flag this on each product page, below the ingredients. if in doubt, try it first on a small area of skin — and talk to us, we can adapt the formula." },
      { q: "what does the asterisk in the ingredient list mean?", a: "that the ingredient is organic. wherever we can we choose organic ingredients, and we mark them with * in the description so you know more about what you are using." },
    ] },
    { title: "orders and shipping", items: [
      { q: "do you ship outside Portugal?", a: "we ship nationally and internationally. shipping is calculated at checkout according to the destination — you see the exact amount before you confirm, with no surprises." },
      { q: "the product i want is sold out. can i still order it?", a: "you can. everything is made by hand in small batches, and some products — the shampoos, the conditioners and the soaps — need time to rest and mature before they can be sent. if one sells out we take the order and let you know as soon as it is ready. we can also prepare larger quantities whenever you need them." },
      { q: "can i ask for something made specifically for me?", a: "yes. we can adapt a formula to what you need — gentler, stronger, or with a different scent. talk to us before ordering." },
    ] },
    { title: "packaging and sustainability", items: [
      { q: "can i return the packaging?", a: "you can, and we are grateful when you do. all our packaging is reusable: bring us an old container — from a deodorant, a hair mask, a candle — and we will reuse it for your next product, with a reuse discount." },
      { q: "can you make candles in my own containers?", a: "we can. if you prefer, we will make your candles in your own jars, mugs or cups — just give us the containers." },
      { q: "why are the products solid?", a: "because we use no water in making them, and because a solid product needs no packaging. day to day they leave less residue and rinse more easily from hair and skin, so you use less water too. and they travel far better: no packaging, and no cabin liquid limits." },
    ] },
    { title: "finding us", items: [
      { q: "where can i find you in person?", a: "we are at fairs and markets through the year — the fairs and markets page has the next dates." },
    ] },
  ] },
  cart: { ...pt.cart, reuseNote: "if you would like to reuse your packaging, write to us — we will sort it out together.", title: "your cart", empty: "your cart is empty for now.", emptyHint: "take a look at our products and choose at your own pace.", browse: "see products", subtotal: "subtotal", shippingNote: "shipping is calculated at the next step, according to the destination.", checkout: "place order", checkingOut: "preparing payment…", remove: "remove", increase: "one more", decrease: "one less", close: "close", continue: "continue browsing", viewCart: "view cart", cancelled: "payment was not completed. your cart is still here whenever you are ready.", stockAdjusted: (name: string, n: number) => n === 0 ? `${name} sold out and was removed from your cart.` : `we can only send ${n} of ${name} for now; the quantity was adjusted.`, maxReached: "there are no more units available right now.", secure: "secure payment through Stripe", itemsCount: (n: number) => n === 1 ? "1 item" : `${n} items`, errorTitle: "we could not continue", errorGeneric: "something went wrong while preparing payment. try again shortly or get in touch.", ok: "ok" },
  checkout: { ...pt.checkout, title: "confirm order", summary: "order summary", shippingTo: "shipping to", shippingMethod: "shipping method", paymentMethod: "payment method", selectPayment: "choose how you'd like to pay", paymentNote: "you can pay by card, MB WAY or apple pay — you choose on the next step, on Stripe's secure page.", creditCard: "credit card", applePay: "apple pay", cardDesc: "mastercard, visa, american express", appleDesc: "fast and secure with apple pay", continuePayment: "continue to payment", subtotal: "subtotal", shipping: "shipping", total: "total", backToCart: "back to cart" },
  order: { ...pt.order, title: "thank you. we received your order.", message: "we prepare every order with care", detail: "we will prepare everything at home and send it as soon as it is ready. if you have any questions, get in touch.", summary: "order summary", reference: "reference", shippingTo: "shipping to", shipping: "shipping", total: "total", notFound: "we could not find this order. if you have just paid, wait a moment and refresh the page.", processing: "we are confirming your payment. this may take a few seconds.", backHome: "back to the home page", emailNote: (email: string) => `we have your contact: ${email}. we will be in touch there about your order.` },
  errors: { notFoundTitle: "we could not find this page.", notFoundText: "it may have moved. take a look at our products or ingredients.", genericTitle: "something went wrong.", genericText: "try again shortly. if it continues, get in touch.", retry: "try again" },
  contact: { title: "get in touch", call: "call", sms: "text", whatsapp: "whatsapp", email: "email" },
};
