import { pt, type Dictionary } from "./pt";

export const fr: Dictionary = {
  ...pt,
  locale: "fr-FR",
  brand: { ...pt.brand, tagline: "fait main, avec amour 🌱", description: "marque portugaise d'hygiène et de beauté naturelle, fabriquée à la main à la maison en petites quantités." },
  nav: { home: "accueil", products: "produits", ingredients: "ingrédients", about: "à propos", care: "soins & durabilité", fairs: "foires et marchés", feedback: "avis", cart: "panier", openMenu: "ouvrir le menu", closeMenu: "fermer le menu", skipToContent: "aller au contenu", homeLink: "lucrescente, page d'accueil" },
  fairs: {
    title: "foires et marchés",
    intro:
      "en plus de la boutique en ligne, vous pouvez aussi nous retrouver dans des foires et marchés locaux — pour voir les produits en vrai, rencontrer les personnes qui vont les utiliser et, parfois, créer des pièces personnalisées sur place. suivez notre instagram pour savoir où nous serons ensuite.",
    comingSoon: "bientôt, plus d'informations sur les prochains événements et foires où nous retrouver !",
    metaDescription: "retrouvez-nous dans les foires et marchés locaux",
  },
  productInfo: {
    notAntiperspirant: "n'est pas un antitranspirant",
    aluminiumFree: "sans aluminium",
    alcoholFree: "sans alcool",
    customisable: "personnalisable",
    waterSavingLabel: "moins d'eau",
    waterSavingText:
      "nous n'utilisons pas d'eau pour fabriquer ce produit. les produits solides laissent beaucoup moins de résidus et se rincent plus facilement des cheveux et de la peau, vous n'avez donc pas besoin d'utiliser autant d'eau pour vous sentir propre — et comme ils ne nécessitent pas d'emballage, nous économisons aussi l'eau utilisée pour fabriquer le plastique.",
    reusableLabel: "réutilisable",
    reusableText:
      "tous nos emballages sont réutilisables. si vous avez un ancien contenant de chez nous ou d'une autre marque, rapportez-le nous et profitez de notre remise réutilisation sur votre prochaine commande !",
    paperWrappedText:
      "nous emballons tous nos produits dans du papier réutilisé, parce que nous privilégions la durabilité et une production consciente plutôt que la consommation inutile.",
    skinSafeLabel: "sûrs pour la peau",
    skinSafeText:
      "nos shampoings solides peuvent aussi être utilisés sur le corps, sans souci : grâce à leurs ingrédients naturels et à l'absence de produits chimiques agressifs, vous pouvez profiter d'un shampoing multifonction tous les jours !",
    contactTitle: "parlez-nous de ce produit",
    contactSuccess: "✓ message envoyé ! merci de nous avoir contactés.",
    contactError:
      "nous n'avons pas pu envoyer votre message. réessayez, ou écrivez-nous directement à",
    contactName: "nom",
    contactNamePlaceholder: "comment vous appelez-vous ?",
    contactEmail: "email",
    contactEmailPlaceholder: "votre email",
    contactMessage: "message",
    contactMessagePlaceholder: "dites-nous ce que vous en pensez, vos questions, vos demandes particulières...",
    contactSend: "envoyer",
    contactSending: "envoi en cours...",
  },
  home: {
    ...pt.home, heroLabel: "fait main, avec soin", heroTitle: "des soins simples, faits avec amour et des ingrédients de confiance.", heroSubtitle: "à la maison, chaque produit commence par un ingrédient que nous connaissons bien — et nous aimons partager son histoire avant qu'il n'arrive sur votre peau.", heroPrimary: "voir tous les produits", heroSecondary: "voir tous les ingrédients", featuredTitle: "nos favoris du moment", cardLink: "découvrir →", productsTitle: "des soins pour vos journées", productsSubtitle: "baumes, shampoings, bougies décorées et bien plus, fabriqués à la main avec des ingrédients choisis avec soin.", productsButton: "voir tous les produits", featuredMoreLink: "voir plus", valuesTitle: "ce qui nous guide", valuesSubtitle: "des ingrédients choisis avec attention, moins de déchets et la liberté de prendre soin de soi à sa manière.", values: ["fait main", "ingrédients honnêtes", "moins de déchets"], storyTitle: "une petite marque, créée avec intention", storyText: "lucrescente a commencé comme un projet entièrement familial — bien avant même d'être un projet — et a grandi, petit à petit, jusqu'à toucher plus de personnes. nous connaissons nos ingrédients, racontons l'histoire de chacun, et continuons à tout fabriquer en petites quantités, avec le même soin qu'au premier jour.", storyLink: "découvrir notre histoire →", ingredientsTitle: "les ingrédients que nous utilisons, un par un", ingredientsSubtitle: "chacun a son histoire et son utilité. choisissez-en un pour découvrir son origine et son rôle 🌿", ingredientsLink: "voir tous les ingrédients →", contactTitle: "commandez vos produits", contactText: "pour toute question, personnalisation ou commande spéciale, contactez-nous.", contactButtons: { call: "appel", sms: "message", whatsapp: "message whatsapp", email: "email" }, shortAbout: "des produits d'hygiène, de beauté et de bien-être faits main par une mère et sa fille, pour un soin personnel plus sain et plus personnalisé.", candleCitronelaName: "citronnelle", candleFlowers: "fleurs séchées", candleMessage: "avec messages personnalisés", candleMassage: "massage", candleAltCitronela1: "trois bougies à la citronnelle dans des pots en verre avec une étiquette noire, sur un tissu fleuri rose et bleu", candleAltCitronela2: "trois bougies dans des pots en verre avec une étiquette noire à côté de fleurs séchées", candleAltMassagem: "un panier en osier avec une bougie dans une boîte métallique, une bougie dans un pot en verre avec un ruban rouge, un pot de sels de bain et un roll-on, sur un tissu de noël avec des lumières", categoryGroupHigiene: "hygiène", categoryGroupBeleza: "beauté", categoryGroupBemEstar: "bien-être", testimonialsLabel: "celles et ceux qui ont déjà essayé", testimonialsTitle: "vos commentaires", testimonialsSubtitle: "reçus dans notre boîte de messages au fil des années, écrits par vous.", testimonialsPrev: "avis précédent", testimonialsNext: "avis suivant", showMore: "voir plus", showLess: "voir moins",
  },
  footer: { line: "lucrescente — fait main, avec amour 🌱", contactsTitle: "contact", pagesTitle: "pages", shipping: "envois nationaux et internationaux sur commande. quantités plus importantes sur demande." },
  products: { ...pt.products, scrollLeft: "voir les catégories précédentes", scrollRight: "voir les catégories suivantes", deodorantFact: "appliquez une fine couche sur une peau propre et sèche — la chaleur du corps aide à bien l'étaler.", solidNote: "produit solide, sans eau dans la formule. gardez-le dans un endroit sec entre deux utilisations pour qu'il dure plus longtemps.", label: "faits main, un par un", title: "nos produits", allCategories: "tous", filterLabel: "catégories", whyItWorks: "pourquoi ça marche", hairTypeNote: "pour quel type de cheveux", recommendedFor: "conseillé pour", notRecommendedFor: "déconseillé pour", mainIngredients: "ingrédients principaux", allergenNoteLabel: "attention", noIngredientsListed: "la liste des ingrédients de ce produit n'est pas encore publiée. contactez-nous pour en savoir plus.", noCopy: "l'histoire de ce produit s'écrit encore à la maison.", noPhoto: "pas encore de photographie", galleryPrevious: "image précédente", galleryNext: "image suivante", galleryOf: (name: string) => `photographies de ${name}`, price: "prix", onRequest: "sur commande", talkToUs: "contactez-nous →", soldOut: "actuellement épuisé. contactez-nous pour commander", soldOutShort: "actuellement épuisé", priceFrom: "à partir de ", addToCart: "ajouter au panier", added: "ajouté au panier", quantity: "quantité", variant: "format", stockLeft: (n: number) => n === 1 ? "plus qu'une unité" : `plus que ${n} unités`, orderMessage: (name: string) => `bonjour ! je voudrais commander : ${name}`, ownContainerLabel: "récipient personnel", candleNote: "si vous le préférez, nous pouvons fabriquer vos bougies dans vos propres pots, tasses ou bols — apportez-nous simplement les contenants.", backToCatalog: "← retour aux produits", relatedTitle: "composez votre coffret", relatedPrev: "produits précédents", relatedNext: "produits suivants", usedInTitle: "où nous utilisons cet ingrédient", emptyCategory: "il n'y a pas encore de produits dans cette catégorie. contactez-nous pour découvrir la suite.", organicNote: "* ingrédient biologique" },
  ingredients: { ...pt.ingredients, label: "d'origine végétale et minérale", title: "les ingrédients que nous utilisons, un par un", subtitle: "chacun a son histoire et son utilité. choisissez-en un pour découvrir son origine et son rôle 🌿", allCategories: "tous", sections: { scientificName: "nom scientifique", origin: "origine", properties: "propriétés", applications: "applications chez lucrescente" }, backToIndex: "← retour aux ingrédients", productsUsing: "produits avec cet ingrédient", noProducts: "nous n'avons pas encore associé cet ingrédient à un produit du catalogue.", searchPlaceholder: "chercher un ingrédient", noResults: "aucun ingrédient ne porte ce nom." },
  about: { ...pt.about, label: "notre histoire", title: "deux façons de penser le soin", intro: "lucrescente est née de la rencontre entre la connaissance scientifique des plantes et une manière sensible et créative de regarder le quotidien.", values: ["entreprise familiale", "écologique et durable", "sûre pour les enfants et les peaux sensibles", "sans perturbateurs endocriniens", "prix accessibles pour toutes et tous"], lucieName: "lucie", lucieText: "je suis docteure en biosciences, en agroécologie — les dernières années ont été passées plongée dans les tournesols, les pollinisateurs et la conservation de la nature. ce même regard attentif, rigoureux et curieux guide le choix des ingrédients et la création de chaque recette lucrescente.", luanaName: "luana", luanaText: "je suis en troisième année de licence en arts plastiques et j'apporte à la marque le soin esthétique, la créativité et la sensibilité. je pense à la manière dont chaque produit est présenté, décrit et intégré aux petits rituels de soin du quotidien.", close: "entre nous, la science rencontre l'expression et chaque produit acquiert sa propre histoire.", backLink: "retour à l'accueil" },
  care: { ...pt.care, label: "soins & durabilité", title: "parce que chaque petit choix compte", intro: "au-delà des ingrédients, chaque produit lucrescente porte une manière de penser — plus naturelle, plus lente et avec moins de déchets. voici pourquoi.", chapters: [
    { slug: "poupamos-agua", title: "nous économisons l'eau", text: "nos shampoings, après-shampoings et savons sont solides — nous n'utilisons pas d'eau dans leur fabrication. dans votre routine, les produits solides laissent moins de résidus et se rincent plus facilement, vous n'avez donc pas besoin d'utiliser autant d'eau. comme ils n'ont pas d'emballage, nous économisons aussi l'eau nécessaire à la fabrication du plastique." },
    { slug: "embalagens", title: "emballages et papiers réutilisés", text: "tous nos emballages sont réutilisables. si vous avez un ancien contenant, apportez-le-nous et nous le réutiliserons pour votre prochain produit avec une remise. nos emballages sont cousus à la main avec des tissus réutilisés — même le fil vient du coton et d'autres fibres recyclées. plus de réutilisation, moins de déchets." },
    { slug: "velas", title: "nos bougies", text: "les bougies lucrescente sont fabriquées avec de la cire végétale de soja, qui fond lentement et uniformément. elles durent ainsi plus longtemps, sans gaspillage de cire, et ne contiennent ni dérivés du pétrole ni parfums synthétiques. la grande majorité des éléments décoratifs que nous utilisons sont naturels : fleurs et feuilles séchées, coquillages, petites pierres... certains éléments végétaux sont même pressés et préparés par nos soins. nous pouvons aussi les fabriquer dans vos propres contenants." },
    { slug: "feito-a-mao", title: "fait main, en petites quantités", text: "les produits lucrescente sont entièrement fabriqués à partir d'ingrédients naturels, de manière artisanale et en petites quantités — pour garantir la qualité des matières premières et le soin de la fabrication. certains produits peuvent être réapprovisionnés chaque jour ; d'autres ont besoin de repos et de maturation. nous acceptons les commandes et les envois nationaux et internationaux." },
    { slug: "desodorizantes", title: "nos déodorants", text: "nos déodorants ne sont pas des anti-transpirants et ne contiennent ni aluminium ni alcool. un déodorant sain ne doit pas bloquer la transpiration ni obstruer les pores. nous préférons respecter le fonctionnement naturel de la peau en contrôlant doucement les bactéries et les odeurs." },
    { slug: "dicas", title: "conseils d'utilisation", text: "nos shampoings solides peuvent aussi être utilisés sur le corps. grâce à leurs ingrédients naturels, certains peuvent aider à apaiser les problèmes de peau. notre cire de soja est hydratante et peut être appliquée directement sur la peau. les produits solides sont aussi très pratiques en voyage, sans limites de liquides." },
    { slug: "biologicos", title: "ingrédients biologiques", text: "chaque fois que possible, nous choisissons des ingrédients biologiques — signalés par * dans les descriptions afin que vous sachiez mieux ce que vous utilisez." },
      ] },
  faq: { ...pt.faq, label: "questions fréquentes", title: "ce qu'on nous demande le plus", intro: "les questions qui nous parviennent le plus souvent par message, réunies ici. si la vôtre n'y est pas, écrivez-nous — nous répondons toujours.", stillAsking: "une question qui ne figure pas ici ?", contactLink: "contactez-nous →", groups: [
    { title: "les produits", items: [
      { q: "quel shampoing solide est fait pour moi ?", a: "il y en a quatre : pour cheveux gras, pour cheveux secs, pour cheveux normaux, et un shampoing doux pour enfants. celui pour cheveux secs est le plus recherché par les personnes au cuir chevelu sensible, et le doux est celui que nous conseillons pour les peaux et cuirs chevelus ultrasensibles, car il ne contient pas d'huiles. en cas de doute, parlez-nous de vos cheveux et nous vous aiderons à choisir." },
      { q: "puis-je utiliser un shampoing solide si je colore ou lisse mes cheveux ?", a: "oui — tous nos shampoings solides conviennent aux cheveux colorés et aux cheveux lissés. nous ne les conseillons pas sur cheveux décolorés, car ils n'ont pas d'effet anti-jaunissement." },
      { q: "le shampoing solide peut-il servir de savon ?", a: "oui. comme ils ne contiennent pas de produits chimiques agressifs, nos shampoings solides peuvent s'utiliser sur le corps — celui pour cheveux secs en particulier est utilisé par des personnes à la peau atopique." },
      { q: "comment conserver les produits solides ?", a: "dans un endroit sec entre deux utilisations. les produits solides ne contiennent pas d'eau, et les garder hors de l'eau quand ils ne servent pas est ce qui les fait durer le plus longtemps." },
      { q: "vos déodorants sont-ils des antitranspirants ?", a: "non. ils ne contiennent ni aluminium ni alcool, et ne bloquent pas la transpiration ni n'obstruent les pores — ils contrôlent les bactéries et les odeurs en douceur, en respectant le fonctionnement naturel de la peau." },
      { q: "j'ai la peau sensible. y a-t-il quelque chose à surveiller ?", a: "plusieurs produits contiennent des huiles essentielles, qui peuvent provoquer une irritation ou une réaction allergique sur les peaux plus sensibles ; les déodorants contiennent du bicarbonate de soude, qui sur certaines peaux irrite les aisselles, surtout après une épilation récente. nous le signalons sur chaque fiche produit, sous les ingrédients. en cas de doute, essayez d'abord sur une petite zone — et parlez-nous-en, nous pouvons adapter la formule." },
      { q: "que signifie l'astérisque dans la liste des ingrédients ?", a: "que cet ingrédient est biologique. dès que possible nous choisissons des ingrédients biologiques et les signalons par * dans la description, pour que vous sachiez mieux ce que vous utilisez." },
    ] },
    { title: "commandes et livraison", items: [
      { q: "livrez-vous hors du Portugal ?", a: "nous expédions au Portugal et à l'international. les frais de port sont calculés au moment du paiement selon la destination — vous voyez le montant exact avant de confirmer, sans surprise." },
      { q: "le produit que je veux est épuisé. puis-je le commander quand même ?", a: "oui. tout est fait à la main en petites quantités, et certains produits — les shampoings, les après-shampoings et les savons — ont besoin de temps de repos et de maturation avant de partir. si l'un est épuisé, nous prenons la commande et vous prévenons dès qu'il est prêt. nous préparons aussi de plus grandes quantités si besoin." },
      { q: "puis-je demander un produit fait sur mesure ?", a: "oui. nous pouvons adapter une formule à vos besoins — plus douce, plus forte, ou avec un autre parfum. parlez-nous-en avant de commander." },
    ] },
    { title: "emballages et durabilité", items: [
      { q: "puis-je rapporter l'emballage ?", a: "oui, et nous vous en remercions. tous nos emballages sont réutilisables : rapportez-nous un ancien contenant — d'un déodorant, d'un masque capillaire, d'une bougie — et nous le réutiliserons pour votre prochain produit, avec une remise de réutilisation." },
      { q: "pouvez-vous faire les bougies dans mes propres contenants ?", a: "oui. si vous préférez, nous faisons vos bougies dans vos propres bocaux, tasses ou coupes — il suffit de nous apporter les récipients." },
      { q: "pourquoi les produits sont-ils solides ?", a: "parce que nous n'utilisons pas d'eau pour les fabriquer, et parce qu'un produit solide se passe d'emballage. au quotidien ils laissent moins de résidus et se rincent plus facilement des cheveux et de la peau, vous consommez donc aussi moins d'eau. et ils voyagent bien mieux : sans emballage et sans limite de liquides en cabine." },
    ] },
    { title: "nous rencontrer", items: [
      { q: "où puis-je vous rencontrer en personne ?", a: "nous sommes présentes sur des foires et marchés tout au long de l'année — la page foires et marchés indique les prochaines dates." },
    ] },
  ] },
  cart: { ...pt.cart, reuseNote: "si vous souhaitez réutiliser vos emballages, écrivez-nous — nous verrons cela ensemble.", title: "votre panier", empty: "votre panier est vide pour le moment.", emptyHint: "découvrez nos produits et choisissez tranquillement.", browse: "voir les produits", subtotal: "sous-total", shippingNote: "les frais de port sont calculés à l'étape suivante selon la destination.", checkout: "finaliser la commande", checkingOut: "préparation du paiement…", remove: "supprimer", increase: "une unité de plus", decrease: "une unité de moins", close: "fermer", continue: "continuer à découvrir les produits", viewCart: "voir le panier", cancelled: "le paiement n'a pas été finalisé. votre panier vous attend.", stockAdjusted: (name: string, n: number) => n === 0 ? `${name} est épuisé et a été retiré du panier.` : `nous ne pouvons envoyer que ${n} unité(s) de ${name} pour le moment ; la quantité a été ajustée.`, maxReached: "aucune unité supplémentaire n'est disponible.", secure: "paiement sécurisé par Stripe", itemsCount: (n: number) => n === 1 ? "1 article" : `${n} articles`, errorTitle: "nous ne pouvons pas continuer", errorGeneric: "un problème est survenu lors de la préparation du paiement. réessayez ou contactez-nous.", ok: "ok" },
  checkout: { ...pt.checkout, title: "confirmez votre commande", summary: "récapitulatif de la commande", shippingTo: "envoi à",  paymentMethod: "méthode de paiement",  paymentNote: "vous pouvez payer par carte, MB WAY ou apple pay — vous choisissez à l'étape suivante, sur la page sécurisée de Stripe.",     continuePayment: "continuer vers le paiement", subtotal: "sous-total", shipping: "frais de port", total: "total", backToCart: "retour au panier" },
  order: { ...pt.order, title: "merci. nous avons reçu votre commande.", message: "nous préparons chaque commande avec soin", detail: "nous allons tout préparer à la maison et envoyer votre commande dès qu'elle sera prête. si vous avez une question, contactez-nous.", summary: "récapitulatif de la commande", reference: "référence", shippingTo: "envio à", shipping: "frais de port", total: "total", notFound: "nous ne trouvons pas cette commande. si vous venez de payer, attendez un instant et actualisez la page.", processing: "nous confirmons votre paiement. cela peut prendre quelques secondes.", backHome: "retour à l'accueil", emailNote: (email: string) => `nous avons votre contact : ${email}. nous vous écrirons à cette adresse au sujet de votre commande.` },
  errors: { notFoundTitle: "cette page est introuvable.", notFoundText: "elle a peut-être changé d'adresse. découvrez nos produits ou nos ingrédients.", genericTitle: "un problème est survenu.", genericText: "réessayez dans un instant. si le problème persiste, contactez-nous.", retry: "réessayer" },
  contact: { title: "contactez-nous", call: "appel", sms: "sms", whatsapp: "whatsapp", email: "email" },
};
