import { pt, type Dictionary } from "./pt";

export const fr: Dictionary = {
  ...pt,
  locale: "fr-FR",
  brand: { ...pt.brand, tagline: "fait main, avec amour 🌱", description: "marque portugaise d'hygiène et de beauté naturelle, fabriquée à la main à la maison en petites quantités." },
  nav: { home: "accueil", products: "produits", ingredients: "ingrédients", about: "à propos", care: "soins & durabilité", cart: "panier", openMenu: "ouvrir le menu", closeMenu: "fermer le menu", skipToContent: "aller au contenu" },
  home: {
    ...pt.home, heroLabel: "fait main, avec soin", heroTitle: "des soins simples, faits avec amour et des ingrédients de confiance.", heroSubtitle: "à la maison, chaque produit commence par un ingrédient que nous connaissons bien — et nous aimons partager son histoire avant qu'il n'arrive sur votre peau.", heroPrimary: "voir tous les produits", heroSecondary: "voir tous les ingrédients", featuredTitle: "nos favoris du moment", cardLink: "découvrir →", productsTitle: "des soins pour vos journées", productsSubtitle: "baumes, shampoings, bougies décorées et bien plus, fabriqués à la main avec des ingrédients choisis avec soin.", productsButton: "voir tous les produits", featuredMoreLink: "voir plus", valuesTitle: "ce qui nous guide", valuesSubtitle: "des ingrédients choisis avec attention, moins de déchets et la liberté de prendre soin de soi à sa manière.", values: ["fait main", "ingrédients honnêtes", "moins de déchets"], storyTitle: "une petite marque, créée avec intention", storyText: "lucrescente a commencé comme un projet entièrement familial — bien avant même d'être un projet — et a grandi, petit à petit, jusqu'à toucher plus de personnes. nous connaissons nos ingrédients, racontons l'histoire de chacun, et continuons à tout fabriquer en petites quantités, avec le même soin qu'au premier jour.", storyLink: "découvrir notre histoire →", ingredientsTitle: "les ingrédients que nous utilisons, un par un", ingredientsSubtitle: "chacun a son histoire et son utilité. choisissez-en un pour découvrir son origine et son rôle 🌿", ingredientsLink: "voir tous les ingrédients →", contactTitle: "commandez vos produits", contactText: "pour toute question, personnalisation ou commande spéciale, contactez-nous.", contactButtons: { call: "appel", sms: "message", whatsapp: "message whatsapp", email: "email" }, shortAbout: "des produits d'hygiène, de beauté et de bien-être faits main par une mère et sa fille, pour un soin personnel plus sain et plus personnalisé.", candleCitronelaName: "citronnelle", candleFlowers: "fleurs séchées", candleMessage: "avec messages personnalisés", candleMassage: "massage", candleAltCitronela1: "trois bougies à la citronnelle dans des pots en verre avec une étiquette noire, sur un tissu fleuri rose et bleu", candleAltCitronela2: "trois bougies dans des pots en verre avec une étiquette noire à côté de fleurs séchées", candleAltMassagem: "un panier en osier avec une bougie dans une boîte métallique, une bougie dans un pot en verre avec un ruban rouge, un pot de sels de bain et un roll-on, sur un tissu de noël avec des lumières", categoryGroupHigiene: "hygiène", categoryGroupBeleza: "beauté", categoryGroupBemEstar: "bien-être", testimonialsLabel: "celles et ceux qui ont déjà essayé", testimonialsTitle: "vos commentaires", testimonialsSubtitle: "reçus dans notre boîte de messages au fil des années, écrits par vous.", testimonialsPrev: "avis précédent", testimonialsNext: "avis suivant", showMore: "voir plus", showLess: "voir moins",
  },
  footer: { line: "lucrescente — fait main, avec amour 🌱", contactsTitle: "contact", pagesTitle: "pages", shipping: "envois nationaux et internationaux sur commande. quantités plus importantes sur demande." },
  products: { ...pt.products, label: "faits main, un par un", title: "nos produits", allCategories: "tous", filterLabel: "catégories", whyItWorks: "pourquoi ça marche", hairTypeNote: "pour quel type de cheveux", recommendedFor: "conseillé pour", notRecommendedFor: "déconseillé pour", mainIngredients: "ingrédients principaux", allergenNoteLabel: "attention", noIngredientsListed: "la liste des ingrédients de ce produit n'est pas encore publiée. contactez-nous pour en savoir plus.", noCopy: "l'histoire de ce produit s'écrit encore à la maison.", price: "prix", onRequest: "sur commande", talkToUs: "contactez-nous →", soldOut: "actuellement épuisé. contactez-nous pour commander", soldOutShort: "actuellement épuisé", addToCart: "ajouter au panier", added: "ajouté au panier", quantity: "quantité", variant: "format", stockLeft: (n: number) => n === 1 ? "plus qu'une unité" : `plus que ${n} unités`, orderMessage: (name: string) => `bonjour ! je voudrais commander : ${name}`, ownContainerLabel: "récipient personnel", candleNote: "si vous le préférez, nous pouvons fabriquer vos bougies dans vos propres pots, tasses ou bols — apportez-nous simplement les contenants.", backToCatalog: "← retour aux produits", relatedTitle: "de la même famille", usedInTitle: "où nous utilisons cet ingrédient", emptyCategory: "il n'y a pas encore de produits dans cette catégorie. contactez-nous pour découvrir la suite.", organicNote: "* ingrédient biologique" },
  ingredients: { ...pt.ingredients, label: "d'origine végétale et minérale", title: "les ingrédients que nous utilisons, un par un", subtitle: "chacun a son histoire et son utilité. choisissez-en un pour découvrir son origine et son rôle 🌿", allCategories: "tous", sections: { scientificName: "nom scientifique", origin: "origine", properties: "propriétés", applications: "applications chez lucrescente" }, backToIndex: "← retour aux ingrédients", productsUsing: "produits avec cet ingrédient", noProducts: "nous n'avons pas encore associé cet ingrédient à un produit du catalogue.", searchPlaceholder: "chercher un ingrédient", noResults: "aucun ingrédient ne porte ce nom." },
  about: { ...pt.about, label: "notre histoire", title: "deux façons de penser le soin", intro: "lucrescente est née de la rencontre entre la connaissance scientifique des plantes et une manière sensible et créative de regarder le quotidien.", promise: "lucrescente est une entreprise familiale, écologique et durable, attentive et sûre pour les enfants et les peaux sensibles. elle ne contient aucun perturbateur endocrinien. nous gardons des prix accessibles, car l'accès aux produits d'hygiène et de beauté doit être ouvert à toutes et tous.", values: ["entreprise familiale", "écologique et durable", "sûre pour les enfants et les peaux sensibles", "sans perturbateurs endocriniens", "prix accessibles pour toutes et tous"], lucieName: "lucie", lucieText: "je suis docteure en biosciences, en agroécologie — les dernières années ont été passées plongée dans les tournesols, les pollinisateurs et la conservation de la nature. ce même regard attentif, rigoureux et curieux guide le choix des ingrédients et la création de chaque recette lucrescente.", luanaName: "luana", luanaText: "je suis en troisième année de licence en arts plastiques et j'apporte à la marque le soin esthétique, la créativité et la sensibilité. je pense à la manière dont chaque produit est présenté, décrit et intégré aux petits rituels de soin du quotidien.", close: "entre nous, la science rencontre l'expression et chaque produit acquiert sa propre histoire.", backLink: "retour à l'accueil" },
  care: { ...pt.care, label: "soins & durabilité", title: "parce que chaque petit choix compte", intro: "au-delà des ingrédients, chaque produit lucrescente porte une manière de penser — plus naturelle, plus lente et avec moins de déchets. voici pourquoi.", chapters: [
    { slug: "poupamos-agua", title: "nous économisons l'eau", text: "nos shampoings, après-shampoings et savons sont solides — nous n'utilisons pas d'eau dans leur fabrication. dans votre routine, les produits solides laissent moins de résidus et se rincent plus facilement, vous n'avez donc pas besoin d'utiliser autant d'eau. comme ils n'ont pas d'emballage, nous économisons aussi l'eau nécessaire à la fabrication du plastique." },
    { slug: "embalagens", title: "emballages et papiers réutilisés", text: "tous nos emballages sont réutilisables. si vous avez un ancien contenant, apportez-le-nous et nous le réutiliserons pour votre prochain produit avec une remise. nos emballages sont cousus à la main avec des tissus réutilisés — même le fil vient du coton et d'autres fibres recyclées. plus de réutilisation, moins de déchets." },
    { slug: "velas", title: "nos bougies", text: "les bougies lucrescente sont fabriquées avec de la cire végétale de soja, qui fond lentement et uniformément. elles durent ainsi plus longtemps, sans gaspillage de cire, et ne contiennent ni dérivés du pétrole ni parfums synthétiques. la grande majorité des éléments décoratifs que nous utilisons sont naturels : fleurs et feuilles séchées, coquillages, petites pierres... certains éléments végétaux sont même pressés et préparés par nos soins. nous pouvons aussi les fabriquer dans vos propres contenants." },
    { slug: "feito-a-mao", title: "fait main, en petites quantités", text: "les produits lucrescente sont entièrement fabriqués à partir d'ingrédients naturels, de manière artisanale et en petites quantités — pour garantir la qualité des matières premières et le soin de la fabrication. certains produits peuvent être réapprovisionnés chaque jour ; d'autres ont besoin de repos et de maturation. nous acceptons les commandes et les envois nationaux et internationaux." },
    { slug: "desodorizantes", title: "nos déodorants", text: "nos déodorants ne sont pas des anti-transpirants et ne contiennent ni aluminium ni alcool. un déodorant sain ne doit pas bloquer la transpiration ni obstruer les pores. nous préférons respecter le fonctionnement naturel de la peau en contrôlant doucement les bactéries et les odeurs." },
    { slug: "dicas", title: "conseils d'utilisation", text: "nos shampoings solides peuvent aussi être utilisés sur le corps. grâce à leurs ingrédients naturels, certains peuvent aider à apaiser les problèmes de peau. notre cire de soja est hydratante et peut être appliquée directement sur la peau. les produits solides sont aussi très pratiques en voyage, sans limites de liquides." },
    { slug: "biologicos", title: "ingrédients biologiques", text: "chaque fois que possible, nous choisissons des ingrédients biologiques — signalés par * dans les descriptions afin que vous sachiez mieux ce que vous utilisez." },
    { slug: "feiras-e-mercados", title: "foires et marchés", text: "en plus de la boutique en ligne, vous pouvez aussi nous retrouver dans des foires et marchés locaux — pour voir les produits en vrai, rencontrer les personnes qui vont les utiliser et, parfois, créer des pièces personnalisées sur place. suivez notre instagram pour savoir où nous serons ensuite." },
  ] },
  cart: { ...pt.cart, title: "votre panier", empty: "votre panier est vide pour le moment.", emptyHint: "découvrez nos produits et choisissez tranquillement.", browse: "voir les produits", subtotal: "sous-total", shippingNote: "les frais de port sont calculés à l'étape suivante selon la destination.", checkout: "finaliser la commande", checkingOut: "préparation du paiement…", remove: "supprimer", increase: "une unité de plus", decrease: "une unité de moins", close: "fermer", continue: "continuer à découvrir les produits", viewCart: "voir le panier", cancelled: "le paiement n'a pas été finalisé. votre panier vous attend.", stockAdjusted: (name: string, n: number) => n === 0 ? `${name} est épuisé et a été retiré du panier.` : `nous ne pouvons envoyer que ${n} unité(s) de ${name} pour le moment ; la quantité a été ajustée.`, maxReached: "aucune unité supplémentaire n'est disponible.", secure: "paiement sécurisé par Stripe", itemsCount: (n: number) => n === 1 ? "1 article" : `${n} articles`, errorTitle: "nous ne pouvons pas continuer", errorGeneric: "un problème est survenu lors de la préparation du paiement. réessayez ou contactez-nous.", ok: "ok" },
  order: { ...pt.order, title: "merci. nous avons reçu votre commande.", message: "nous préparons chaque commande avec soin", detail: "nous allons tout préparer à la maison et envoyer votre commande dès qu'elle sera prête. si vous avez une question, contactez-nous.", summary: "récapitulatif de la commande", reference: "référence", shippingTo: "envoi à", shipping: "frais de port", total: "total", notFound: "nous ne trouvons pas cette commande. si vous venez de payer, attendez un instant et actualisez la page.", processing: "nous confirmons votre paiement. cela peut prendre quelques secondes.", backHome: "retour à l'accueil", emailNote: (email: string) => `la confirmation a été envoyée à ${email}.` },
  errors: { notFoundTitle: "cette page est introuvable.", notFoundText: "elle a peut-être changé d'adresse. découvrez nos produits ou nos ingrédients.", genericTitle: "un problème est survenu.", genericText: "réessayez dans un instant. si le problème persiste, contactez-nous.", retry: "réessayer" },
  contact: { title: "contactez-nous", call: "appel", sms: "sms", whatsapp: "whatsapp", email: "email" },
};
