import type { ProductLocale } from "./product-locales";

/**
 * English/French overrides for the 60-ingredient catalogue. `scientific_name`
 * is Latin and isn't translated. Populate `copy` per slug (see
 * src/data/ingredients.json for the canonical PT source + exact slugs).
 */
export type IngredientCopy = { name: string; origin: string; properties: string; applications: string };

const categoryNames: Record<string, Partial<Record<ProductLocale, string>>> = {
  "Óleos Vegetais": { en: "vegetable oils", fr: "huiles végétales" },
  "Óleos Essenciais": { en: "essential oils", fr: "huiles essentielles" },
  Manteigas: { en: "butters", fr: "beurres" },
  Hidrolatos: { en: "hydrosols", fr: "hydrolats" },
  "Ceras e Emulsionantes": { en: "waxes & emulsifiers", fr: "cires et émulsifiants" },
  Argilas: { en: "clays", fr: "argiles" },
  Ativos: { en: "active ingredients", fr: "actifs" },
  "Outros Ingredientes": { en: "other ingredients", fr: "autres ingrédients" },
};

const copy: Record<string, Partial<Record<ProductLocale, IngredientCopy>>> = {
  "oleo-de-baunilha-macerado": {
    en: { name: "Macerated Vanilla Oil", origin: "Obtained by macerating vanilla pods in a base vegetable oil, a traditional process that slowly transfers the vanilla's aroma and some of its compounds into the oil over several weeks.", properties: "Sweet, enveloping aroma associated with a feeling of comfort; the base oil contributes emollient properties that help nourish and soften the skin.", applications: "Used as an aromatic ingredient in balms and body oils, for a warm, comforting scent." },
    fr: { name: "Huile de vanille macérée", origin: "Obtenue par macération de gousses de vanille dans une huile végétale de base, un procédé traditionnel qui transfère lentement l'arôme et certains composés de la vanille à l'huile au fil des semaines.", properties: "Arôme doux et enveloppant, associé à une sensation de confort ; l'huile de base apporte des propriétés émollientes qui aident à nourrir et adoucir la peau.", applications: "Utilisée comme ingrédient aromatique dans les baumes et huiles corporelles, pour un parfum chaud et réconfortant." },
  },
  "oleo-de-abacate": {
    en: { name: "Avocado Oil", origin: "Extracted from avocado pulp, the fruit of a tree native to Central America, now grown across several tropical and subtropical regions.", properties: "Rich, slightly buttery texture, with a good concentration of essential fatty acids (oleic and linoleic) and vitamin E, penetrating hair fibres well and helping to deeply nourish drier hair and skin.", applications: "Used in the conditioner, where it adds to the nourishment already provided by shea butter and sweet almond and argan oils." },
    fr: { name: "Huile d'avocat", origin: "Extraite de la pulpe d'avocat, fruit d'un arbre originaire d'Amérique centrale, aujourd'hui cultivé dans plusieurs régions tropicales et subtropicales.", properties: "Texture riche et légèrement onctueuse, avec une bonne concentration d'acides gras essentiels (oléique et linoléique) et de vitamine E, pénétrant bien la fibre capillaire et aidant à nourrir en profondeur cheveux et peaux plus secs.", applications: "Utilisée dans l'après-shampoing, où elle renforce la nutrition apportée par le beurre de karité et les huiles d'amande douce et d'argan." },
  },
  "oleo-de-coco": {
    en: { name: "Coconut Oil", origin: "Extracted from coconut flesh, the fruit of a tropical palm grown in coastal regions around the world, including Southeast Asia and parts of South America.", properties: "Rich in saturated fatty acids (mainly lauric acid), it melts at skin temperature and forms a protective film that helps retain hydration and reduce transepidermal water loss. Light texture and relatively fast absorption compared with other vegetable butters. Also widely used in hair care, where it helps reduce protein loss from the hair fibre.", applications: "One of our most widely used base oils — found in body balms, solid soaps, solid conditioners and our oily hair shampoo, where it helps cleanse without stripping all the scalp's natural oil." },
    fr: { name: "Huile de coco", origin: "Extraite de la pulpe de noix de coco, fruit d'un palmier tropical cultivé dans les régions côtières du monde entier, notamment en Asie du Sud-Est et dans certaines régions d'Amérique du Sud.", properties: "Riche en acides gras saturés (surtout l'acide laurique), elle fond à la température de la peau et forme un film protecteur qui aide à retenir l'hydratation et à réduire la perte d'eau transépidermique. Texture légère et absorption relativement rapide comparée à d'autres beurres végétaux. Également très utilisée en soins capillaires, où elle aide à réduire la perte de protéines de la fibre capillaire.", applications: "L'une de nos huiles de base les plus utilisées — présente dans les baumes corporels, savons solides, après-shampoings solides et notre shampoing cheveux gras, où elle aide à nettoyer sans retirer tout le sébum naturel du cuir chevelu." },
  },
  "oleo-de-neem": {
    en: { name: "Neem Oil", origin: "Extracted from the seeds of the neem tree, native to the Indian subcontinent, where it has been used in traditional remedies for centuries.", properties: "A dense oil with a distinctive aroma, traditionally valued in scalp and skin care, especially in formulas designed for skin or scalps prone to imbalance. Always used in small percentages due to its concentration.", applications: "Used in small percentages in hair and body products designed for scalps or skin with more specific needs." },
    fr: { name: "Huile de neem", origin: "Extraite des graines de l'arbre de neem, originaire du sous-continent indien, où elle est utilisée depuis des siècles dans les remèdes traditionnels.", properties: "Huile dense à l'odeur marquée, traditionnellement appréciée dans les soins du cuir chevelu et de la peau, en particulier dans les formules pensées pour les peaux ou cuirs chevelus sujets aux déséquilibres. Toujours utilisée à faible pourcentage en raison de sa concentration.", applications: "Utilisée à faible pourcentage dans des produits capillaires et corporels pensés pour les cuirs chevelus ou peaux aux besoins plus spécifiques." },
  },
  "oleo-de-ricino": {
    en: { name: "Castor Oil", origin: "Extracted from the seeds of the castor plant, a fast-growing plant cultivated in tropical and subtropical regions, including parts of India and Brazil.", properties: "Dense, viscous and highly emollient texture, with good capacity to retain moisture and form a protective layer on the surface of skin and hair. Rich in ricinoleic acid, an uncommon fatty acid that gives it this characteristic thick consistency. Frequently used in products for lips, hair, eyebrows and nails, where its viscosity helps hold other ingredients in place.", applications: "A component of our lip balms, where its viscosity helps create that enveloping texture, and also present in our oily hair shampoo, where it helps nourish the ends without weighing down the roots." },
    fr: { name: "Huile de ricin", origin: "Extraite des graines du ricin, une plante à croissance rapide cultivée dans les régions tropicales et subtropicales, notamment en Inde et au Brésil.", properties: "Texture dense, visqueuse et très émolliente, avec une bonne capacité à retenir l'humidité et à former une couche protectrice à la surface de la peau et des cheveux. Riche en acide ricinoléique, un acide gras peu courant qui lui confère cette consistance épaisse caractéristique. Souvent utilisée dans les produits pour les lèvres, les cheveux, les sourcils et les ongles, où sa viscosité aide à fixer les autres ingrédients.", applications: "Présente dans nos baumes à lèvres, où sa viscosité aide à créer cette texture enveloppante, ainsi que dans notre shampoing cheveux gras, où elle aide à nourrir les pointes sans alourdir les racines." },
  },
  "oleo-vegetal-de-amendoas-doces": {
    en: { name: "Sweet Almond Vegetable Oil", origin: "Extracted from sweet almonds, the fruit of a tree grown mainly in the Mediterranean basin.", properties: "Light texture, quickly absorbed, rich in vitamin E and essential fatty acids (oleic and linoleic), which help nourish and soften the skin without leaving a greasy feel. Widely used as a massage oil for its good slip.", applications: "Used as a base oil in body and massage oils." },
    fr: { name: "Huile végétale d'amande douce", origin: "Extraite des amandes douces, fruit d'un arbre cultivé surtout dans le bassin méditerranéen.", properties: "Texture légère et rapidement absorbée, riche en vitamine E et en acides gras essentiels (oléique et linoléique), qui aident à nourrir et adoucir la peau sans laisser de sensation grasse. Très utilisée comme huile de massage pour sa bonne glisse.", applications: "Utilisée comme huile de base dans les huiles corporelles et de massage." },
  },
  "oleo-vegetal-de-argao": {
    en: { name: "Argan Vegetable Oil", origin: "Extracted from the kernels of the argan tree, native to southwestern Morocco, traditionally produced by hand by local cooperatives.", properties: "Rich in essential fatty acids and vitamin E, it is highly valued in hair and facial care for its silky texture and ability to nourish without weighing down, helping to control frizz and add shine to hair.", applications: "Used in facial oils and nourishing hair products, including our oily hair shampoo, where it helps nourish hair without leaving a heavy feeling." },
    fr: { name: "Huile végétale d'argan", origin: "Extraite des amandons de l'arganier, arbre originaire du sud-ouest du Maroc, traditionnellement produite de façon artisanale par des coopératives locales.", properties: "Riche en acides gras essentiels et en vitamine E, elle est très appréciée dans les soins capillaires et du visage pour sa texture soyeuse et sa capacité à nourrir sans alourdir, aidant à contrôler les frisottis et à donner de la brillance aux cheveux.", applications: "Utilisée dans les huiles pour le visage et les produits capillaires nourrissants, y compris notre shampoing cheveux gras, où elle aide à nourrir les cheveux sans laisser de sensation de lourdeur." },
  },
  "oleo-essencial-de-alecrim": {
    en: { name: "Rosemary Essential Oil", origin: "Extracted by steam distillation of rosemary leaves, a Mediterranean aromatic shrub.", properties: "Herbaceous, stimulating aroma, traditionally associated with revitalising hair care and a feeling of energy. Like all essential oils, it is used in very low concentrations and always diluted.", applications: "Used in small amounts in hair products, for an aroma that gives energy first thing in the morning." },
    fr: { name: "Huile essentielle de romarin", origin: "Extraite par distillation à la vapeur des feuilles de romarin, un arbuste aromatique méditerranéen.", properties: "Arôme herbacé et stimulant, traditionnellement associé aux soins capillaires revitalisants et à une sensation d'énergie. Comme toutes les huiles essentielles, elle est utilisée à de très faibles concentrations et toujours diluée.", applications: "Utilisée en petite quantité dans les produits capillaires, pour un arôme qui donne de l'énergie dès le matin." },
  },
  "oleo-essencial-de-alecrim-qt-cineol": {
    en: { name: "Rosemary CT Cineole Essential Oil", origin: "Cineole-chemotype rosemary essential oil, extracted by distillation of rosemary leaves.", properties: "Has a herbaceous, fresh and invigorating aroma, valued in hair care formulas for its feeling of cleanliness and energy. Traditionally associated with strengthening hair and stimulating the scalp, helping to promote hair growth.", applications: "Used in a small amount in the hair mask, where it contributes to the formula's fresh, revitalising aroma." },
    fr: { name: "Huile essentielle de romarin CT cinéole", origin: "Huile essentielle de romarin chémotypée à cinéole, extraite par distillation des feuilles de romarin.", properties: "Possède un arôme herbacé, frais et tonifiant, apprécié dans les formules de soin capillaire pour sa sensation de propreté et d'énergie. Traditionnellement associée au renforcement des cheveux et à la stimulation du cuir chevelu, aidant à favoriser la pousse des cheveux.", applications: "Utilisée en petite quantité dans le masque capillaire, où elle contribue à l'arôme frais et revitalisant de la formule." },
  },
  "oleo-essencial-de-bergamota": {
    en: { name: "Bergamot Essential Oil", origin: "Extracted from bergamot peel, a citrus fruit grown mainly in southern Italy.", properties: "Citrus and floral aroma, widely used in natural perfumery for its balanced aromatic profile, which combines citrus freshness with a softer floral note. Traditionally considered relaxing and calming, and associated with anti-inflammatory and skin-regenerating properties.", applications: "Used as an aromatic note in perfumed products, always in small amounts to balance more intense aromas." },
    fr: { name: "Huile essentielle de bergamote", origin: "Extraite de l'écorce de bergamote, un agrume cultivé surtout dans le sud de l'Italie.", properties: "Arôme citronné et floral, très utilisé en parfumerie naturelle pour son profil aromatique équilibré, qui associe la fraîcheur citronnée à une note florale plus douce. Traditionnellement considérée comme relaxante et apaisante, et associée à des propriétés anti-inflammatoires et régénérantes pour la peau.", applications: "Utilisée comme note aromatique dans les produits parfumés, toujours en petite quantité pour équilibrer des arômes plus intenses." },
  },
  "oleo-essencial-de-camomila-romana": {
    en: { name: "Roman Chamomile Essential Oil", origin: "Extracted by distillation of Roman chamomile flowers.", properties: "Soft, sweetish aroma, traditionally associated with a calming effect, both through its scent and the compounds present in the oil. Always used highly diluted given its potency.", applications: "Used in small amounts in products for sensitive skin, always with great care in dosing." },
    fr: { name: "Huile essentielle de camomille romaine", origin: "Extraite par distillation des fleurs de camomille romaine.", properties: "Arôme doux et légèrement sucré, traditionnellement associé à un effet calmant, à la fois par son odeur et par les composés présents dans l'huile. Toujours utilisée très diluée compte tenu de sa puissance.", applications: "Utilisée en petite quantité dans les produits pour peaux sensibles, toujours avec beaucoup de précaution dans le dosage." },
  },
  "oleo-essencial-de-erva-principe": {
    en: { name: "Lemongrass Essential Oil", origin: "Also known as West Indian lemongrass, it is extracted by distillation of the leaves of this tropical plant.", properties: "Intense, fresh citrus aroma, widely used in aromatherapy and natural perfumery for its ability to refresh and energise an environment or product.", applications: "Used as a refreshing aromatic note in body products, great for summer days." },
    fr: { name: "Huile essentielle de citronnelle", origin: "Également appelée citronnelle des Indes, elle est extraite par distillation des feuilles de cette plante tropicale.", properties: "Arôme citronné intense et frais, très utilisé en aromathérapie et en parfumerie naturelle pour sa capacité à rafraîchir et dynamiser un environnement ou un produit.", applications: "Utilisée comme note aromatique rafraîchissante dans les produits corporels, parfaite pour les journées d'été." },
  },
  "oleo-essencial-de-erva-principe-citratus": {
    en: { name: "Lemongrass Essential Oil (Citratus)", origin: "Extracted by distillation of lemongrass leaves, an aromatic tropical grass known for its fresh, citrus scent.", properties: "Has a lemony, fresh and revitalising aroma. In cosmetics, it is used mainly for its aromatic note and the feeling of cleanliness it adds to formulas.", applications: "Used in a small amount in the oily hair shampoo, where it gives the formula a fresh citrus aroma and an invigorating feeling during washing." },
    fr: { name: "Huile essentielle de citronnelle (Citratus)", origin: "Extraite par distillation des feuilles de citronnelle, une graminée aromatique d'origine tropicale connue pour son parfum frais et citronné.", properties: "Possède un arôme citronné, frais et revitalisant. En cosmétique, elle est utilisée surtout pour sa note aromatique et la sensation de propreté qu'elle apporte aux formules.", applications: "Utilisée en petite quantité dans le shampoing cheveux gras, où elle apporte à la formule un arôme citronné frais et une sensation tonifiante pendant le lavage." },
  },
  "oleo-essencial-de-eucalipto-radiata": {
    en: { name: "Eucalyptus Radiata Essential Oil", origin: "Extracted by distillation of eucalyptus leaves, a tree native to Australia.", properties: "Fresh, penetrating aroma, traditionally associated with a feeling of clear breathing and invigorating environments, being a eucalyptus variety considered gentler than others.", applications: "Used in bath products and aromatic diffusers." },
    fr: { name: "Huile essentielle d'eucalyptus radiata", origin: "Extraite par distillation des feuilles d'eucalyptus, un arbre originaire d'Australie.", properties: "Arôme frais et pénétrant, traditionnellement associé à une sensation de respiration dégagée et à des ambiances tonifiantes, s'agissant d'une variété d'eucalyptus considérée comme plus douce que d'autres.", applications: "Utilisée dans les produits de bain et les diffuseurs aromatiques." },
  },
  "oleo-essencial-de-geranio-rosa": {
    en: { name: "Rose Geranium Essential Oil", origin: "Extracted from the leaves and flowers of rose geranium, an aromatic plant grown mainly in Africa and the Mediterranean.", properties: "Floral, slightly sweet aroma with rose-like notes, highly appreciated in natural perfumery and associated with a balancing effect in formulas for combination skin.", applications: "Used as a floral note in perfumed products." },
    fr: { name: "Huile essentielle de géranium rosat", origin: "Extraite des feuilles et des fleurs du géranium rosat, une plante aromatique cultivée surtout en Afrique et dans le bassin méditerranéen.", properties: "Arôme floral et légèrement sucré, aux notes rappelant la rose, très apprécié en parfumerie naturelle et associé à un effet équilibrant dans les formules pour peaux mixtes.", applications: "Utilisée comme note florale dans les produits parfumés." },
  },
  "oleo-essencial-de-hortela-pimenta": {
    en: { name: "Peppermint Essential Oil", origin: "Extracted by distillation of peppermint leaves.", properties: "Intense, refreshing aroma, with an immediate feeling of coolness on the skin when properly diluted and applied, thanks to the menthol present in the plant.", applications: "Used in small amounts in refreshing products for feet and body, and in the oily hair shampoo, where it gives that immediate cooling effect on the scalp." },
    fr: { name: "Huile essentielle de menthe poivrée", origin: "Extraite par distillation des feuilles de menthe poivrée.", properties: "Arôme intense et rafraîchissant, procurant une sensation immédiate de fraîcheur sur la peau lorsqu'elle est correctement diluée et appliquée, grâce au menthol présent dans la plante.", applications: "Utilisée en petite quantité dans les produits rafraîchissants pour les pieds et le corps, ainsi que dans le shampoing cheveux gras, où elle procure cet effet de fraîcheur immédiate sur le cuir chevelu." },
  },
  "oleo-essencial-de-laranja-doce": {
    en: { name: "Sweet Orange Essential Oil", origin: "Extracted from sweet orange peel, one of the most widely used citrus essential oils in natural cosmetics.", properties: "Sweet, cheerful citrus aroma, associated with a feeling of well-being and often used to balance more intense aromas in other blends.", applications: "Used as an aromatic note in various products, for a cheerful scent that pleases almost everyone." },
    fr: { name: "Huile essentielle d'orange douce", origin: "Extraite de l'écorce d'orange douce, l'une des huiles essentielles d'agrumes les plus utilisées en cosmétique naturelle.", properties: "Arôme citronné doux et gai, associé à une sensation de bien-être, souvent utilisé pour équilibrer des arômes plus intenses dans d'autres mélanges.", applications: "Utilisée comme note aromatique dans divers produits, pour un parfum gai qui plaît à presque tout le monde." },
  },
  "oleo-essencial-de-lavanda": {
    en: { name: "Lavender Essential Oil", origin: "Extracted by distillation of lavender flowers, one of the most versatile and well-known essential oils.", properties: "Floral, herbaceous aroma, traditionally associated with a calming, anti-inflammatory and healing effect, being one of the most studied essential oils and one of the few considered relatively safe for more frequent use, always diluted.", applications: "Used in relaxing and night-care products, one of the most requested scents by our customers." },
    fr: { name: "Huile essentielle de lavande", origin: "Extraite par distillation des fleurs de lavande, l'une des huiles essentielles les plus polyvalentes et les plus connues.", properties: "Arôme floral et herbacé, traditionnellement associé à un effet calmant, anti-inflammatoire et cicatrisant, étant l'une des huiles essentielles les plus étudiées et l'une des rares considérées comme relativement sûres pour un usage plus fréquent, toujours diluée.", applications: "Utilisée dans les produits relaxants et de soin du soir, l'un des parfums les plus demandés par nos clients." },
  },
  "oleo-essencial-de-lavanda-4042-blend": {
    en: { name: "Lavender Essential Oil 40/42 (blend)", origin: "Aromatic blend based on lavender essential oil, selected for its balanced and consistent floral profile.", properties: "Has a soft, recognisable floral aroma, associated with a feeling of calm and comfort. The blend format offers a stable fragrance suited to hair-care formulas. Beyond its scent, it's traditionally valued for its calming effect on the skin, and can even be used after hair removal.", applications: "Used in a small amount in the dry hair shampoo, where it contributes to the formula's soft, comforting aroma." },
    fr: { name: "Huile essentielle de lavande 40/42 (blend)", origin: "Mélange aromatique à base d'huile essentielle de lavande, sélectionné pour son profil floral équilibré et constant.", properties: "Possède un arôme floral doux et reconnaissable, associé à une sensation de calme et de confort. Le format blend offre une fragrance stable, adaptée aux formules de soin capillaire. Au-delà de son parfum, elle est traditionnellement appréciée pour son effet calmant sur la peau, et peut même être utilisée après une épilation.", applications: "Utilisée en petite quantité dans le shampoing cheveux secs, où elle contribue à l'arôme doux et réconfortant de la formule." },
  },
  "oleo-essencial-de-limao": {
    en: { name: "Lemon Essential Oil", origin: "Cold-pressed from lemon peel.", properties: "Vivid, energising citrus aroma, widely used in natural cleaning products and perfumery for the immediate feeling of freshness it conveys. Rich in antioxidants, it's also valued in hair care for the way it helps promote shine.", applications: "Used as a fresh aromatic note in body products and in the oily hair shampoo, for an invigorating effect and an extra feeling of cleanliness." },
    fr: { name: "Huile essentielle de citron", origin: "Extraite à froid de l'écorce de citron.", properties: "Arôme citronné vif et énergisant, très utilisé dans les produits d'entretien naturels et en parfumerie pour la sensation immédiate de fraîcheur qu'il procure. Riche en antioxydants, elle est également appréciée en soin capillaire pour la façon dont elle aide à faire briller les cheveux.", applications: "Utilisée comme note aromatique fraîche dans les produits corporels et dans le shampoing cheveux gras, pour un effet tonifiant et une sensation de propreté supplémentaire." },
  },
  "oleo-essencial-de-palmarosa": {
    en: { name: "Palmarosa Essential Oil", origin: "Extracted by distillation from an aromatic grass native to India, related to citronella.", properties: "Soft floral aroma, with notes reminiscent of rose; widely used in natural skin care, sometimes used as a more affordable alternative to true rose oils in perfumery. It's also valued for its action against the bacteria and microorganisms responsible for unpleasant odours, which is why it's widely used in natural deodorants.", applications: "Used as a floral note in facial and body products, a more affordable aroma for anyone who loves rose." },
    fr: { name: "Huile essentielle de palmarosa", origin: "Extraite par distillation d'une graminée aromatique originaire d'Inde, apparentée à la citronnelle.", properties: "Arôme floral doux, aux notes rappelant la rose ; très utilisée dans les soins de la peau naturels, parfois employée comme alternative plus accessible aux huiles de rose véritable en parfumerie. Elle est également appréciée pour son action contre les bactéries et micro-organismes responsables des mauvaises odeurs, ce qui explique son usage fréquent dans les déodorants naturels.", applications: "Utilisée comme note florale dans les produits pour le visage et le corps, un arôme plus accessible pour qui aime la rose." },
  },
  "oleo-essencial-de-petitgrain": {
    en: { name: "Petitgrain Essential Oil", origin: "Extracted by distillation of the leaves and twigs of the bitter orange tree, distinct from the oil extracted from the flower (neroli) or the peel.", properties: "Green, slightly floral and woody aroma, widely used in natural perfumery as a base note that adds depth to more complex blends.", applications: "Used as a base aromatic note in perfumed products, adding depth to more elaborate blends." },
    fr: { name: "Huile essentielle de petitgrain", origin: "Extraite par distillation des feuilles et des rameaux du bigaradier, distincte de l'huile extraite de la fleur (néroli) ou de l'écorce.", properties: "Arôme vert, légèrement floral et boisé, très utilisé en parfumerie naturelle comme note de fond qui apporte de la profondeur à des mélanges plus complexes.", applications: "Utilisée comme note aromatique de fond dans les produits parfumés, apportant de la profondeur à des mélanges plus élaborés." },
  },
  "oleo-essencial-de-ravintsara": {
    en: { name: "Ravintsara Essential Oil", origin: "Extracted from the leaves of a tree grown mainly in Madagascar.", properties: "Fresh, woody aroma, with notes reminiscent of eucalyptus, traditionally associated with invigorating environments and used in diffusers to create a fresher atmosphere.", applications: "Used in diffusers and aromatic bath products, for a fresher atmosphere at home." },
    fr: { name: "Huile essentielle de ravintsara", origin: "Extraite des feuilles d'un arbre cultivé principalement à Madagascar.", properties: "Arôme frais et boisé, aux notes rappelant l'eucalyptus, traditionnellement associé à des ambiances tonifiantes et utilisé dans les diffuseurs pour créer une atmosphère plus fraîche.", applications: "Utilisée dans les diffuseurs et les produits de bain aromatiques, pour une atmosphère plus fraîche à la maison." },
  },
  "oleo-essencial-de-tea-tree": {
    en: { name: "Tea Tree Essential Oil", origin: "Extracted by distillation of the leaves of the tea tree, native to Australia, where it was traditionally used by Aboriginal peoples.", properties: "Fresh, slightly medicinal aroma; one of the most studied essential oils in natural cosmetics, traditionally associated with oily or blemish-prone skin, helping to convey a feeling of cleanliness.", applications: "Used in small amounts in purifying products, for an extra feeling of cleanliness." },
    fr: { name: "Huile essentielle de tea tree", origin: "Extraite par distillation des feuilles de l'arbre à thé, originaire d'Australie, où elle était traditionnellement utilisée par les peuples aborigènes.", properties: "Arôme frais et légèrement médicinal ; l'une des huiles essentielles les plus étudiées en cosmétique naturelle, traditionnellement associée aux peaux à tendance grasse ou à imperfections, aidant à procurer une sensation de propreté.", applications: "Utilisée en petite quantité dans les produits purifiants, pour une sensation de propreté supplémentaire." },
  },
  "oleo-essencial-de-ylang-ylang": {
    en: { name: "Ylang-Ylang Essential Oil", origin: "Extracted from the flowers of the cananga tree, a tropical tree grown mainly in Madagascar and Southeast Asia.", properties: "Intense, exotic floral aroma, highly valued in natural perfumery as a striking central note, traditionally associated with a feeling of relaxation.", applications: "Used as a striking floral note in perfumed products, for anyone who loves a more intense, enveloping aroma." },
    fr: { name: "Huile essentielle d'ylang-ylang", origin: "Extraite des fleurs du cananga, un arbre tropical cultivé surtout à Madagascar et en Asie du Sud-Est.", properties: "Arôme floral intense et exotique, très apprécié en parfumerie naturelle comme note centrale marquante, traditionnellement associée à une sensation de relaxation.", applications: "Utilisée comme note florale marquante dans les produits parfumés, pour qui aime un arôme plus intense et enveloppant." },
  },
  "oleo-essencial-de-gengibre": {
    en: { name: "Ginger Essential Oil", origin: "Extracted by distillation of ginger root, a spice grown mainly in tropical Asia.", properties: "Warm, spicy and woody aroma, traditionally associated with a feeling of energy and warmth, widely used in invigorating formulas.", applications: "Used in a small amount in aromatic products, to add a warm, enveloping note." },
    fr: { name: "Huile essentielle de gingembre", origin: "Extraite par distillation de la racine de gingembre, une épice cultivée surtout en Asie tropicale.", properties: "Arôme chaud, épicé et boisé, traditionnellement associé à une sensation d'énergie et de chaleur, très utilisé dans les formules tonifiantes.", applications: "Utilisée en petite quantité dans les produits aromatiques, pour ajouter une note chaude et enveloppante." },
  },
  "oleo-essencial-de-canela": {
    en: { name: "Cinnamon Essential Oil", origin: "Extracted from cinnamon bark or leaves, a spice of Asian origin grown mainly in Sri Lanka.", properties: "Warm, sweet and spiced aroma, highly recognisable, always used in very small amounts as it is an intense, potent oil.", applications: "Used in minimal amounts in winter aromatic products, for a spiced, comforting note." },
    fr: { name: "Huile essentielle de cannelle", origin: "Extraite de l'écorce ou des feuilles de cannelle, une épice d'origine asiatique cultivée surtout au Sri Lanka.", properties: "Arôme chaud, sucré et épicé, très reconnaissable, toujours utilisé en très petites quantités car il s'agit d'une huile intense et puissante.", applications: "Utilisée en quantités minimes dans les produits aromatiques d'hiver, pour une note épicée et réconfortante." },
  },
  "oleo-essencial-de-patchouli": {
    en: { name: "Patchouli Essential Oil", origin: "Extracted by distillation of patchouli leaves, an aromatic plant native to Southeast Asia.", properties: "Earthy, woody and long-lasting aroma, widely used in natural perfumery as a fixative, helping other scents last longer.", applications: "Used in a small amount as an aromatic base in perfumed products, to add depth and fix the scent." },
    fr: { name: "Huile essentielle de patchouli", origin: "Extraite par distillation des feuilles de patchouli, une plante aromatique originaire d'Asie du Sud-Est.", properties: "Arôme terreux, boisé et persistant, très utilisé en parfumerie naturelle comme fixateur, aidant les autres parfums à durer plus longtemps.", applications: "Utilisée en petite quantité comme base aromatique dans les produits parfumés, pour apporter de la profondeur et fixer le parfum." },
  },
  "oleo-essencial-de-ho-wood": {
    en: { name: "Ho Wood Essential Oil", origin: "Extracted by distillation of ho wood, a tree from China often used as a more sustainable alternative to rosewood.", properties: "Floral, slightly woody aroma, rich in linalool, traditionally associated with a calming, balancing effect.", applications: "Used as a gentle, sustainable alternative in calming aromatic products." },
    fr: { name: "Huile essentielle de bois de hô", origin: "Extraite par distillation du bois de hô, un arbre originaire de Chine souvent utilisé comme alternative plus durable au bois de rose.", properties: "Arôme floral et légèrement boisé, riche en linalol, traditionnellement associé à un effet calmant et équilibrant.", applications: "Utilisée comme alternative douce et durable dans les produits aromatiques apaisants." },
  },
  "manteiga-de-cacau": {
    en: { name: "Cocoa Butter", origin: "Extracted from the seeds of the cacao tree, a tropical tree grown mainly in Central and South America and West Africa.", properties: "Solid and brittle at room temperature, rich in natural antioxidants (polyphenols) that help protect its own fat from oxidation. Forms a protective barrier on the skin, helps retain moisture and is traditionally associated with maintaining elasticity in areas subject to greater stretching.", applications: "Used in denser body balms and creams, especially in formulas designed for very dry skin or for the colder months of the year." },
    fr: { name: "Beurre de cacao", origin: "Extrait des fèves du cacaoyer, un arbre tropical cultivé surtout en Amérique centrale et du Sud ainsi qu'en Afrique de l'Ouest.", properties: "Solide et cassant à température ambiante, riche en antioxydants naturels (polyphénols) qui aident à protéger sa propre matière grasse de l'oxydation. Forme une barrière protectrice sur la peau, aide à retenir l'humidité et est traditionnellement associé au maintien de l'élasticité dans les zones soumises à plus de tension.", applications: "Utilisé dans des baumes et crèmes corporelles plus denses, notamment dans les formules pensées pour les peaux très sèches ou pour les mois les plus froids de l'année." },
  },
  "manteiga-de-karite": {
    en: { name: "Shea Butter", origin: "Extracted from the seeds of the shea tree, native to the West African savannah, where it has been produced by hand for generations.", properties: "Dense, buttery texture, rich in fatty acids (stearic and oleic) and vitamin E, melting gently on contact with skin. Deeply nourishes and helps restore comfort to very dry, rough skin or skin damaged by cold and wind. Its unsaponifiable fraction is often associated with maintaining skin elasticity.", applications: "Our favourite base butter for balms and moisturising lip balms — it combines very well with sweet almond and argan oils, a trio we often use in products designed for drier skin and hair." },
    fr: { name: "Beurre de karité", origin: "Extrait des graines du karité, arbre originaire de la savane d'Afrique de l'Ouest, où il est produit de façon artisanale depuis des générations.", properties: "Texture dense et onctueuse, riche en acides gras (stéarique et oléique) et en vitamine E, fondant doucement au contact de la peau. Nourrit en profondeur et aide à restaurer le confort des peaux très sèches, rugueuses ou abîmées par le froid et le vent. Sa fraction insaponifiable est souvent associée au maintien de l'élasticité de la peau.", applications: "Notre beurre de base préféré pour les baumes et baumes à lèvres hydratants — il se marie très bien avec les huiles d'amande douce et d'argan, un trio que nous utilisons souvent dans les produits pensés pour les peaux et cheveux plus secs." },
  },
  "hidrolato-de-alecrim": {
    en: { name: "Rosemary Hydrosol", origin: "Aromatic water obtained by distillation of rosemary leaves, a Mediterranean aromatic plant.", properties: "Toning and refreshing, traditionally associated with hair care and a feeling of scalp revitalisation. Also used as a facial toner for combination skin, for its slightly astringent effect.", applications: "Used in hair products and revitalising toners, a frequent choice for anyone looking to add energy to their scalp-care routine." },
    fr: { name: "Hydrolat de romarin", origin: "Eau aromatique obtenue par distillation des feuilles de romarin, une plante aromatique méditerranéenne.", properties: "Tonifiant et rafraîchissant, traditionnellement associé aux soins capillaires et à une sensation de revitalisation du cuir chevelu. Également utilisé comme tonique visage pour les peaux mixtes, pour son effet légèrement astringent.", applications: "Utilisé dans les produits capillaires et les toniques revitalisants, un choix fréquent pour qui cherche à dynamiser sa routine de soin du cuir chevelu." },
  },
  "hidrolato-de-camomila-romana": {
    en: { name: "Roman Chamomile Hydrosol", origin: "Aromatic water obtained by distillation of Roman chamomile flowers, a plant common throughout Europe.", properties: "Helps soothe the skin and reduce the feeling of discomfort in more reactive areas, being a common choice for sensitive skin and gentler care routines, including night care or after sun exposure.", applications: "Used in gentle formulas designed for sensitive skin, including some of our daily facial toners." },
    fr: { name: "Hydrolat de camomille romaine", origin: "Eau aromatique obtenue par distillation des fleurs de camomille romaine, une plante commune dans toute l'Europe.", properties: "Aide à apaiser la peau et à réduire la sensation d'inconfort dans les zones plus réactives, étant un choix courant pour les peaux sensibles et les routines de soin plus douces, y compris les soins du soir ou après une exposition au soleil.", applications: "Utilisé dans des formules douces pensées pour les peaux sensibles, y compris certains de nos toniques visage à usage quotidien." },
  },
  "hidrolato-de-hortela-pimenta": {
    en: { name: "Peppermint Hydrosol", origin: "Aromatic water obtained by distillation of peppermint leaves.", properties: "Provides an immediate refreshing feeling on the skin thanks to the effect of the menthol present in the plant, being associated with revitalising products and use on hot days or after physical activity.", applications: "Used in refreshing sprays and foot products, and also in the oily hair shampoo, where it reinforces the feeling of freshness and cleanliness on the scalp." },
    fr: { name: "Hydrolat de menthe poivrée", origin: "Eau aromatique obtenue par distillation des feuilles de menthe poivrée.", properties: "Procure une sensation de fraîcheur immédiate sur la peau grâce à l'effet du menthol présent dans la plante, étant associé aux produits revitalisants et à une utilisation par temps chaud ou après une activité physique.", applications: "Utilisé dans les brumes rafraîchissantes et les produits pour les pieds, ainsi que dans le shampoing cheveux gras, où il renforce la sensation de fraîcheur et de propreté du cuir chevelu." },
  },
  "hidrolato-de-lavanda": {
    en: { name: "Lavender Hydrosol", origin: "Aromatic water obtained by steam distillation of lavender flowers, a by-product of the same process that extracts the essential oil.", properties: "Refreshing and calming, helps balance combination-to-oily skin and is often associated with reducing the feeling of tension in the skin. Contains a much gentler concentration of lavender's active compounds than the essential oil, which makes it safe for spraying directly onto skin or face.", applications: "Used as the aqueous base in the oily hair shampoo, helping to soothe the scalp, and also in facial products and relaxing sprays." },
    fr: { name: "Hydrolat de lavande", origin: "Eau aromatique obtenue par distillation à la vapeur des fleurs de lavande, un sous-produit du même procédé qui permet d'extraire l'huile essentielle.", properties: "Rafraîchissant et calmant, aide à équilibrer les peaux mixtes à grasses et est souvent associé à la réduction de la sensation de tension de la peau. Contient une concentration bien plus douce des composés actifs de la lavande que l'huile essentielle, ce qui le rend sûr pour une pulvérisation directe sur la peau ou le visage.", applications: "Utilisé comme base aqueuse dans le shampoing cheveux gras, aidant à apaiser le cuir chevelu, ainsi que dans les produits pour le visage et les brumes relaxantes." },
  },
  "acido-estearico": {
    en: { name: "Stearic Acid", origin: "A saturated fatty acid present in many vegetable fats, used in cosmetics as a thickener and co-emulsifier.", properties: "Helps stabilise emulsions (mixtures of water and oil that would otherwise separate) and gives creams and lotions a creamy texture, body and velvety feel. Also contributes to the formula's stability over time.", applications: "Used as a thickener in body and facial creams, and also in the oily hair shampoo, where it helps give the formula body and stabilise it over time." },
    fr: { name: "Acide stéarique", origin: "Un acide gras saturé présent dans de nombreuses matières grasses végétales, utilisé en cosmétique comme épaississant et co-émulsifiant.", properties: "Aide à stabiliser les émulsions (mélanges d'eau et d'huile qui se sépareraient autrement) et confère aux crèmes et lotions une texture crémeuse, du corps et une sensation veloutée. Contribue également à la stabilité de la formule dans le temps.", applications: "Utilisé comme épaississant dans les crèmes corporelles et faciales, ainsi que dans le shampoing cheveux gras, où il aide à donner du corps à la formule et à la stabiliser dans le temps." },
  },
  "alcool-cetilico": {
    en: { name: "Cetyl Alcohol", origin: "A fatty alcohol of vegetable origin (not to be confused with ethyl alcohol), typically derived from coconut or palm oil.", properties: "A gentle thickener and emollient, it helps stabilise emulsions and leaves skin feeling soft and velvety, without the drying effect of ethyl alcohol — in fact, it has the opposite effect, contributing to the feeling of hydration in the final product.", applications: "Used to give body and stability to creams and lotions." },
    fr: { name: "Alcool cétylique", origin: "Un alcool gras d'origine végétale (à ne pas confondre avec l'alcool éthylique), généralement dérivé de l'huile de coco ou de palme.", properties: "Épaississant et émollient doux, il aide à stabiliser les émulsions et laisse la peau douce et veloutée, sans l'effet asséchant de l'alcool éthylique — il a en réalité l'effet inverse, contribuant à la sensation d'hydratation du produit final.", applications: "Utilisé pour donner du corps et de la stabilité aux crèmes et lotions." },
  },
  "cera-autoemulsionante-olivem": {
    en: { name: "OliveM Self-Emulsifying Wax", origin: "A vegetable emulsifier derived from olive oil, developed to create stable emulsions without relying on synthetic ingredients.", properties: "Allows water and oil to be blended in a stable, long-lasting way, resulting in light, non-greasy textures and a silky feel on the skin. Considered a gentle-profile emulsifier, also suitable for more sensitive skin.", applications: "Used as the main emulsifier in creams and lotions, whenever we want a lighter texture and fast absorption." },
    fr: { name: "Cire auto-émulsifiante OliveM", origin: "Un émulsifiant végétal dérivé de l'huile d'olive, développé pour créer des émulsions stables sans recourir à des ingrédients synthétiques.", properties: "Permet de mélanger l'eau et l'huile de façon stable et durable, donnant des textures légères, non grasses, et une sensation soyeuse sur la peau. Considéré comme un émulsifiant au profil doux, également adapté aux peaux plus sensibles.", applications: "Utilisée comme émulsifiant principal dans les crèmes et lotions, chaque fois que nous voulons une texture plus légère et une absorption rapide." },
  },
  "cera-de-abelha-amarela": {
    en: { name: "Yellow Beeswax", origin: "Produced by bees to build the hive's honeycombs; the yellow variant retains the natural colour and scent of honey and pollen.", properties: "Gives balms and candles solid structure and texture, while also helping form a protective, slightly occlusive barrier on the skin that reduces water loss. Has gentle emollient properties and contributes to the stability and shelf life of the formulas it is part of, by creating a texture more resistant to heat.", applications: "An essential ingredient in our natural candles, where it gives body and helps them burn more evenly, and also used in lip balms and solid creams to give them structure." },
    fr: { name: "Cire d'abeille jaune", origin: "Produite par les abeilles pour construire les rayons de la ruche ; la variante jaune conserve la couleur et le parfum naturels du miel et du pollen.", properties: "Confère structure et texture solide aux baumes et bougies, tout en aidant à former une barrière protectrice et légèrement occlusive sur la peau, réduisant la perte d'eau. Possède des propriétés émollientes douces et contribue à la stabilité et à la durée de conservation des formules dans lesquelles elle entre, en créant une texture plus résistante à la chaleur.", applications: "Ingrédient essentiel dans nos bougies naturelles, où elle donne du corps et aide à une combustion plus régulière, également utilisée dans les baumes à lèvres et crèmes solides pour leur donner de la structure." },
  },
  "cera-de-soja": {
    en: { name: "Soy Wax", origin: "A vegetable wax obtained from soybean oil, a renewable and ecologically sustainable resource — a natural alternative to paraffin wax and other petroleum derivatives.", properties: "Solid at room temperature, it melts and sets slowly and evenly, without creating a 'well' around the wick or wasting wax — which also makes it an economical choice. It burns cleaner and slower than paraffin, with less soot. It is safe to the touch, biodegradable and, being moisturising, can be used directly on the skin.", applications: "The base of our candles, where it guarantees an even, long-lasting burn and, thanks to the essential oils we add, releases a light, therapeutic aroma as it burns. Beyond candles, the same wax gives us solid air fresheners — to scent drawers and cupboards or melt in a wax warmer — and, melted, it can also serve as a massage oil or be rubbed directly onto the skin as a comforting solid 'perfume'." },
    fr: { name: "Cire de soja", origin: "Une cire végétale obtenue à partir de l'huile de soja, une ressource renouvelable et écologiquement durable — une alternative naturelle aux cires de paraffine et autres dérivés du pétrole.", properties: "Solide à température ambiante, elle fond et se solidifie lentement et uniformément, sans créer de « puits » autour de la mèche ni gaspiller de cire — ce qui en fait aussi un choix économique. Elle brûle plus proprement et plus lentement que la paraffine, avec moins de suie. Elle est sans danger au toucher, biodégradable et, étant hydratante, peut être utilisée directement sur la peau.", applications: "La base de nos bougies, où elle garantit une combustion uniforme et durable et, grâce aux huiles essentielles que nous y ajoutons, libère un arôme léger et thérapeutique en brûlant. En dehors des bougies, cette même cire nous permet de créer des désodorisants solides — pour parfumer tiroirs et armoires ou faire fondre dans un brûleur — et, une fois fondue, elle peut aussi servir d'huile de massage ou être appliquée directement sur la peau comme un « parfum » solide et réconfortant." },
  },
  "cera-emulsionante-btms": {
    en: { name: "BTMS Emulsifying Wax", origin: "A vegetable-derived emulsifier used mainly in hair products, made up of cetearyl alcohol and a gentle, positively charged surfactant.", properties: "Gives a creamy texture and helps conditioning ingredients adhere to the hair fibre, making it easier to detangle and reducing static. Leaves hair feeling soft and easier to comb.", applications: "Used in our conditioners and hair masks, to make hair easier to detangle." },
    fr: { name: "Cire émulsifiante BTMS", origin: "Un émulsifiant d'origine végétale utilisé principalement dans les produits capillaires, composé d'alcool cétéarylique et d'un tensioactif doux à charge positive.", properties: "Confère une texture crémeuse et aide les ingrédients conditionneurs à adhérer à la fibre capillaire, facilitant le démêlage et réduisant l'électricité statique. Laisse les cheveux doux et plus faciles à coiffer.", applications: "Utilisée dans nos après-shampoings et masques capillaires, pour faciliter le démêlage des cheveux." },
  },
  "argila-branca": {
    en: { name: "White CosKAO Clay", origin: "Also called kaolin, it is a naturally occurring mineral clay, one of the gentlest among cosmetic clays.", properties: "Absorbs excess oiliness without over-drying, thanks to its mineral structure that captures impurities and sebum on the skin's surface without penetrating deeply. It is the gentlest of cosmetic clays, suitable even for sensitive or dry skin that needs more delicate cleansing.", applications: "Used in our gentlest facial masks and in the oily hair shampoo, where white CosKAO clay helps cleanse without harshness." },
    fr: { name: "Argile blanche CosKAO", origin: "Également appelée kaolin, c'est une argile minérale d'origine naturelle, l'une des plus douces parmi les argiles cosmétiques.", properties: "Absorbe l'excès de sébum sans trop assécher, grâce à sa structure minérale qui capte les impuretés et le sébum à la surface de la peau sans pénétrer en profondeur. C'est la plus douce des argiles cosmétiques, adaptée même aux peaux sensibles ou sèches qui ont besoin d'un nettoyage plus délicat.", applications: "Utilisée dans nos masques faciaux les plus doux et dans le shampoing cheveux gras, où l'argile blanche CosKAO aide à nettoyer sans agresser." },
  },
  "argila-verde-superfina": {
    en: { name: "Superfine Green Clay", origin: "A mineral clay rich in iron oxide and other minerals, responsible for its greenish colour.", properties: "Has a greater absorbing power than white clay, effectively capturing excess sebum and impurities, making it suitable for oilier skin or skin prone to blemishes. Its fine ('superfine') texture allows more even application and more controlled drying in facial masks.", applications: "Used in our purifying facial masks, and also in the oily hair shampoo, where it helps absorb excess oiliness from the scalp without drying out the ends." },
    fr: { name: "Argile verte surfine", origin: "Une argile minérale riche en oxyde de fer et en d'autres minéraux, responsables de sa teinte verdâtre.", properties: "Possède un pouvoir absorbant plus important que l'argile blanche, captant efficacement l'excès de sébum et les impuretés, ce qui la rend adaptée aux peaux plus grasses ou à tendance imperfections. Sa texture fine (« surfine ») permet une application plus uniforme et un séchage plus maîtrisé dans les masques faciaux.", applications: "Utilisée dans nos masques faciaux purifiants, ainsi que dans le shampoing cheveux gras, où elle aide à absorber l'excès de sébum du cuir chevelu sans assécher les pointes." },
  },
  "coenzima-q10": {
    en: { name: "Coenzyme Q10", origin: "A compound naturally present in the cells of the human body, also synthesised for cosmetic use from vegetable sources.", properties: "A recognised antioxidant, it helps protect the skin from oxidative stress caused by environmental factors and is often associated with anti-ageing care, being used in low concentrations due to its high potency.", applications: "Added in small amounts to our more complete facial serums and creams." },
    fr: { name: "Coenzyme Q10", origin: "Un composé naturellement présent dans les cellules du corps humain, également synthétisé pour un usage cosmétique à partir de sources végétales.", properties: "Antioxydant reconnu, il aide à protéger la peau du stress oxydatif causé par des facteurs environnementaux et est souvent associé aux soins anti-âge, étant utilisé à faible concentration en raison de sa forte puissance.", applications: "Ajoutée en petite quantité à nos sérums et crèmes visage les plus complets." },
  },
  "conservante-cosgard": {
    en: { name: "Cosgard Preservative", origin: "A vegetable-derived preservative (based on benzyl alcohol and dehydroacetic acid), widely used in natural cosmetics as an alternative to parabens.", properties: "Protects water-based formulas against the growth of bacteria, mould and yeast, safely extending their shelf life. Effective across a wide pH range and widely accepted in certified natural cosmetics.", applications: "Used in small percentages in all products containing water — including the oily hair shampoo — to make sure they reach you safely." },
    fr: { name: "Conservateur Cosgard", origin: "Un conservateur d'origine végétale (à base d'alcool benzylique et d'acide déhydroacétique), largement utilisé en cosmétique naturelle comme alternative aux parabènes.", properties: "Protège les formules à teneur aqueuse contre le développement de bactéries, moisissures et levures, prolongeant leur durée de conservation en toute sécurité. Efficace sur une large plage de pH et largement accepté en cosmétique certifiée naturelle.", applications: "Utilisé à faible pourcentage dans tous les produits contenant de l'eau — y compris le shampoing cheveux gras — pour garantir qu'ils vous parviennent en toute sécurité." },
  },
  "d-pantenol-provitamina-b5": {
    en: { name: "D-Panthenol (Provitamin B5)", origin: "A precursor form of vitamin B5, converted into pantothenic acid when applied to skin or hair.", properties: "Moisturising and soothing, it helps retain moisture in the skin's outermost layer and is often used in hair products to add shine, softness and reduce roughness in the strands. It also contributes to a feeling of comfort on irritated skin.", applications: "Added to creams, lotions and the oily hair shampoo, where it helps offset the more intense cleansing effect, leaving hair soft rather than rough." },
    fr: { name: "D-Panthénol (Provitamine B5)", origin: "Une forme précurseur de la vitamine B5, convertie en acide pantothénique lorsqu'elle est appliquée sur la peau ou les cheveux.", properties: "Hydratant et apaisant, il aide à retenir l'humidité dans la couche la plus superficielle de la peau et est souvent utilisé dans les produits capillaires pour apporter brillance, douceur et réduire la rugosité des cheveux. Contribue également à la sensation de confort des peaux irritées.", applications: "Ajouté aux crèmes, lotions et au shampoing cheveux gras, où il aide à compenser l'effet nettoyant plus intense, laissant les cheveux doux plutôt que rêches." },
  },
  "tensioativo-sci": {
    en: { name: "SCI Surfactant", origin: "Sodium Cocoyl Isethionate — a gentle surfactant derived from coconut oil, widely used in natural cosmetics as an alternative to harsher surfactants such as sodium lauryl sulfate.", properties: "Produces a creamy, dense foam, and cleanses skin and hair without being as harsh on the skin barrier as other common surfactants, reducing the feeling of dryness or tightness after washing.", applications: "Used as the cleansing base in solid soaps and in the oily hair shampoo, where it is mainly responsible for removing excess oiliness without aggravating the scalp." },
    fr: { name: "Tensioactif SCI", origin: "Sodium Cocoyl Isethionate — un tensioactif doux dérivé de l'huile de coco, largement utilisé en cosmétique naturelle comme alternative à des tensioactifs plus agressifs comme le sodium lauryl sulfate.", properties: "Produit une mousse crémeuse et dense, et nettoie la peau et les cheveux sans être aussi agressif pour la barrière cutanée que d'autres tensioactifs courants, réduisant la sensation de sécheresse ou de tiraillement après le lavage.", applications: "Utilisé comme base nettoyante dans les savons solides et dans le shampoing cheveux gras, où il est principalement responsable de l'élimination de l'excès de sébum sans agresser le cuir chevelu." },
  },
  "vitamina-e": {
    en: { name: "Vitamin E", origin: "Also known as tocopherol, it is a fat-soluble antioxidant naturally present in vegetable oils such as sunflower and wheat germ oil.", properties: "Helps protect vegetable oils from oxidation (extending products' shelf life and preventing rancid odours), and contributes to a feeling of comfort and softness on the skin. As an antioxidant, it also helps neutralise free radicals generated by environmental exposure.", applications: "Added to oils, balms and solid conditioners as a natural antioxidant, helping extend the shelf life of our formulas with a higher vegetable-oil content." },
    fr: { name: "Vitamine E", origin: "Également connue sous le nom de tocophérol, c'est un antioxydant liposoluble naturellement présent dans les huiles végétales comme l'huile de tournesol et de germe de blé.", properties: "Aide à protéger les huiles végétales de l'oxydation (prolongeant la durée de conservation des produits et évitant l'apparition d'une odeur de rance), et contribue à la sensation de confort et de douceur de la peau. En tant qu'antioxydant, elle aide également à neutraliser les radicaux libres générés par l'exposition environnementale.", applications: "Ajoutée aux huiles, baumes et après-shampoings solides comme antioxydant naturel, aidant à prolonger la durée de vie de nos formules à forte teneur en huiles végétales." },
  },
  "vitamina-e-tocoferol-70": {
    en: { name: "Vitamin E (Tocopherol 70%)", origin: "An antioxidant concentrate rich in tocopherols, supplied in an oil base with 70% vitamin E.", properties: "Helps protect vegetable oils from oxidation and contributes to a feeling of softness and comfort in hair.", applications: "Used in the conditioner as an antioxidant for the oil phase, helping protect the formula and extend its stability." },
    fr: { name: "Vitamine E (Tocophérol 70 %)", origin: "Un concentré antioxydant riche en tocophérols, fourni dans une base huileuse à 70 % de vitamine E.", properties: "Aide à protéger les huiles végétales de l'oxydation et contribue à une sensation de douceur et de confort pour les cheveux.", applications: "Utilisée dans l'après-shampoing comme antioxydant de la phase huileuse, aidant à protéger la formule et à prolonger sa stabilité." },
  },
  "aloe-vera": {
    en: { name: "Aloe Vera", origin: "A succulent plant native to the Arabian Peninsula, now grown in hot, dry regions around the world. It has been known for millennia for the clear gel held within its leaves.", properties: "Hydrates without weighing down, helps soothe irritated or sun-exposed skin and contributes to a feeling of comfort on sensitive skin. Nourishes and softens, helps fade scars and marks, and is antioxidant — which makes it useful in helping prevent blemishes from appearing. The gel is made up mostly of water, complemented by polysaccharides that help form a protective film on the skin's surface, retaining moisture. It also contains small amounts of vitamins (A, C, E) and minerals, and is generally well tolerated even on reactive or redness-prone skin.", applications: "We use aloe vera as a moisturising base in body creams and in some of our facial masks, usually combined with soothing hydrosols such as Roman chamomile or lavender to reinforce the feeling of skin comfort. In our face, hand and body soaps, it is always organic aloe vera, harvested and prepared by us on the spot — not a processed gel bought ready-made." },
    fr: { name: "Aloé vera", origin: "Une plante succulente originaire de la péninsule Arabique, aujourd'hui cultivée dans les régions chaudes et sèches du monde entier. Connue depuis des millénaires pour le gel transparent conservé à l'intérieur de ses feuilles.", properties: "Hydrate sans alourdir, aide à apaiser la peau irritée ou exposée au soleil et contribue à la sensation de confort des peaux sensibles. Nourrit et adoucit, aide à atténuer cicatrices et marques, et possède des propriétés antioxydantes — ce qui la rend utile pour aider à prévenir l'apparition de boutons. Le gel est composé majoritairement d'eau, complétée par des polysaccharides qui aident à former un film protecteur à la surface de la peau, retenant l'humidité. Il contient également de petites quantités de vitamines (A, C, E) et de minéraux, et est généralement bien toléré même par les peaux réactives ou sujettes aux rougeurs.", applications: "Nous utilisons l'aloé vera comme base hydratante dans les crèmes corporelles et dans certains de nos masques faciaux, généralement associée à des hydrolats apaisants comme la camomille romaine ou la lavande pour renforcer la sensation de confort de la peau. Dans nos savons visage, mains et corps, c'est toujours de l'aloé vera biologique, récolté et préparé par nous sur le moment — et non un gel transformé acheté tout prêt." },
  },
  "amido-de-milho": {
    en: { name: "Corn Starch", origin: "Extracted from the endosperm of corn, a fine powder widely used in natural cosmetics as an alternative to synthetic talcs.", properties: "Absorbs excess moisture and gives the skin a silky, dry feel, without the respiratory risks associated with the very fine mineral particles found in conventional talc. It is also gentle enough for use on more sensitive areas of the body.", applications: "Used in body powders and as a base in natural deodorant formulas, helping to keep skin feeling dry throughout the day." },
    fr: { name: "Amidon de maïs", origin: "Extrait de l'endosperme du maïs, une poudre fine largement utilisée en cosmétique naturelle comme alternative aux talcs synthétiques.", properties: "Absorbe l'excès d'humidité et procure à la peau une sensation soyeuse et sèche, sans les risques respiratoires associés aux particules minérales très fines présentes dans le talc conventionnel. Suffisamment doux pour être utilisé sur les zones plus sensibles du corps.", applications: "Utilisé dans les poudres corporelles et comme base dans les formules de déodorant naturel, aidant à conserver une sensation de peau sèche tout au long de la journée." },
  },
  "bicarbonato-de-sodio": {
    en: { name: "Sodium Bicarbonate", origin: "A widely available mineral compound (NaHCO₃), used for centuries in personal hygiene and household cleaning products.", properties: "Slightly abrasive and odour-neutralising — it helps balance the skin's pH and neutralise the compounds responsible for body odour, rather than simply masking them. It is a classic ingredient in natural deodorants and, at low concentrations, in fine-textured gentle scrubs.", applications: "The base of our natural deodorant line, and used in small amounts in some body scrubs to give a slightly granular texture." },
    fr: { name: "Bicarbonate de sodium", origin: "Un composé minéral largement disponible (NaHCO₃), utilisé depuis des siècles dans les produits d'hygiène et d'entretien ménager.", properties: "Légèrement abrasif et neutralisant d'odeurs — il aide à équilibrer le pH de la peau et à neutraliser les composés responsables des odeurs corporelles, plutôt que de simplement les masquer. C'est un ingrédient classique dans les déodorants naturels et, à faible concentration, dans les gommages doux à texture fine.", applications: "Base de notre gamme de déodorant naturel, et utilisé en petite quantité dans certains gommages corporels pour apporter une texture légèrement granuleuse." },
  },
  "cacau-natural": {
    en: { name: "Natural Cocoa", origin: "A powder obtained from the roasted, ground seeds of the cacao tree (Theobroma cacao), rich in natural antioxidants.", properties: "Gives a characteristic aroma and colour, along with antioxidant properties (flavonoids) that help protect formulas from oxidation. Also occasionally used as a natural colourant in exfoliating or lightly tinted products.", applications: "Used as an aromatic ingredient and natural colourant in some of our limited-edition scrubs and soaps." },
    fr: { name: "Cacao naturel", origin: "Une poudre obtenue à partir des fèves torréfiées et moulues du cacaoyer (Theobroma cacao), riche en antioxydants naturels.", properties: "Apporte un arôme et une couleur caractéristiques, ainsi que des propriétés antioxydantes (flavonoïdes) qui aident à protéger les formules de l'oxydation. Également utilisé ponctuellement comme colorant naturel dans des produits exfoliants ou légèrement teintés.", applications: "Utilisé comme ingrédient aromatique et colorant naturel dans certains de nos gommages et savons en édition limitée." },
  },
  "cavalinha-em-po": {
    en: { name: "Horsetail Powder", origin: "A silica-rich plant, traditionally used in infusions and natural cosmetics for its reputed strengthening properties.", properties: "Traditionally associated with strengthening hair and nails, thanks to its natural silica content and other minerals that are part of the structure of these tissues. Also used in hair masks for its fine texture.", applications: "Used as a powder in hair masks and treatments, and also in the oily hair shampoo, where it helps strengthen hair while the scalp is deeply cleansed." },
    fr: { name: "Poudre de prêle", origin: "Une plante riche en silice, traditionnellement utilisée en infusion et en cosmétique naturelle pour sa réputation fortifiante.", properties: "Traditionnellement associée au renforcement des cheveux et des ongles, grâce à sa teneur naturelle en silice et à d'autres minéraux qui font partie de la structure de ces tissus. Également utilisée en poudre dans les masques capillaires pour sa texture fine.", applications: "Utilisée en poudre dans les masques et soins capillaires, ainsi que dans le shampoing cheveux gras, où elle aide à renforcer les cheveux tout en nettoyant le cuir chevelu en profondeur." },
  },
  "farinha-de-aveia": {
    en: { name: "Oat Flour", origin: "Obtained by milling oat grains (Avena sativa), one of the oldest ingredients used in home skin care.", properties: "Helps soothe sensitive or irritated skin, thanks to the beta-glucans and natural compounds present in the grain, and provides gentle physical exfoliation when used as a powder or ground flakes.", applications: "Used in gentle scrubs, soothing facial masks and in the oily hair shampoo, where it helps cleanse and soothe the scalp." },
    fr: { name: "Farine d'avoine", origin: "Obtenue par la mouture des grains d'avoine (Avena sativa), l'un des plus anciens ingrédients utilisés dans les soins de la peau maison.", properties: "Aide à apaiser les peaux sensibles ou irritées, grâce aux bêta-glucanes et aux composés naturels présents dans le grain, et procure une légère exfoliation physique lorsqu'elle est utilisée en poudre ou en flocons moulus.", applications: "Utilisée dans des gommages doux, des masques faciaux apaisants et dans le shampoing cheveux gras, où elle aide à nettoyer et apaiser le cuir chevelu." },
  },
  "farinha-de-coco": {
    en: { name: "Coconut Flour", origin: "A by-product of coconut milk production, obtained from the dried, ground pulp.", properties: "Fine, slightly granular texture, helps absorb excess oiliness and provides gentle exfoliation, suitable for regular use without being too harsh on the skin.", applications: "Used in body scrubs, masks and in the oily hair shampoo, where it helps give the formula body and cleanse gently." },
    fr: { name: "Farine de coco", origin: "Un sous-produit de la production de lait de coco, obtenu à partir de la pulpe séchée et moulue.", properties: "Texture fine et légèrement granuleuse, aide à absorber l'excès de sébum et procure une exfoliation douce, adaptée à un usage régulier sans être trop agressive pour la peau.", applications: "Utilisée dans les gommages corporels, les masques et dans le shampoing cheveux gras, où elle aide à donner du corps à la formule et à nettoyer en douceur." },
  },
  "glicerina-vegetal": {
    en: { name: "Vegetable Glycerin", origin: "Obtained from vegetable oils (such as coconut or palm), it is a natural by-product of soap making.", properties: "A humectant — it draws water from the environment and helps retain it in the skin's outermost layer — which makes it one of the most widely used moisturising ingredients in natural cosmetics. It also helps soften the texture of soaps and creams, and is generally very well tolerated, even by sensitive skin.", applications: "Present in almost all our solid soaps and in creams and lotions, as a moisturising agent that helps soften the final texture of the product." },
    fr: { name: "Glycérine végétale", origin: "Obtenue à partir d'huiles végétales (comme la noix de coco ou le palme), c'est un sous-produit naturel de la fabrication du savon.", properties: "Un humectant — elle attire l'eau de l'environnement et aide à la retenir dans la couche la plus superficielle de la peau — ce qui en fait l'un des ingrédients hydratants les plus utilisés en cosmétique naturelle. Elle aide également à adoucir la texture des savons et crèmes, et est généralement très bien tolérée, même par les peaux sensibles.", applications: "Présente dans presque tous nos savons solides ainsi que dans les crèmes et lotions, comme agent hydratant qui aide à adoucir la texture finale du produit." },
  },
  "hibisco-flor-moida": {
    en: { name: "Hibiscus (Ground Flower)", origin: "A deep red tropical flower, traditionally used in infusions and, more recently, in natural cosmetics.", properties: "Rich in natural antioxidants and gentle organic acids; its vibrant colour is often used in natural formulas both for the visual effect and for the revitalising properties associated with the plant.", applications: "Used ground in facial masks and scrubs, for the lovely colour it gives our products and the texture it provides." },
    fr: { name: "Hibiscus (fleur moulue)", origin: "Une fleur tropicale d'un rouge intense, traditionnellement utilisée en infusion et, plus récemment, en cosmétique naturelle.", properties: "Riche en antioxydants naturels et en acides organiques doux ; sa couleur vive est souvent exploitée dans les formules naturelles à la fois pour l'effet visuel et pour les propriétés revitalisantes associées à la plante.", applications: "Utilisé moulu dans les masques faciaux et gommages, pour la jolie couleur qu'il apporte à nos produits et la texture qu'il procure." },
  },
  "sal-de-epsom": {
    en: { name: "Epsom Salt", origin: "Magnesium sulfate, a natural mineral named after the English town of Epsom, where it was discovered in a spring.", properties: "Traditionally used in relaxing baths, associated with a feeling of muscle relief and relaxation after more tiring days or intense physical activity. Dissolves easily in warm water.", applications: "Used in our relaxing bath salts, ideal for the end of a tiring day." },
    fr: { name: "Sel d'Epsom", origin: "Sulfate de magnésium, un minéral naturel qui doit son nom à la ville anglaise d'Epsom, où il a été découvert dans une source.", properties: "Traditionnellement utilisé dans les bains relaxants, associé à une sensation de soulagement musculaire et de détente après des journées plus fatigantes ou une activité physique intense. Se dissout facilement dans l'eau chaude.", applications: "Utilisé dans nos sels de bain relaxants, idéaux pour la fin d'une journée fatigante." },
  },
  "sementes-de-papoila": {
    en: { name: "Poppy Seeds", origin: "Small, crunchy-textured seeds, long used in both cooking and exfoliating cosmetics.", properties: "Provide gentle, even physical exfoliation thanks to their rounded shape, suitable for regular use without micro-tears in the skin, unlike scrubs with more irregular or sharp-edged particles.", applications: "Used as an exfoliating agent in soaps and body scrubs, for a delicate yet effective effect." },
    fr: { name: "Graines de pavot", origin: "De petites graines à la texture croquante, utilisées depuis longtemps aussi bien en cuisine qu'en cosmétique exfoliante.", properties: "Procurent une exfoliation physique douce et uniforme grâce à leur forme arrondie, adaptée à un usage régulier sans micro-lésions de la peau, contrairement aux gommages aux particules plus irrégulières ou coupantes.", applications: "Utilisées comme agent exfoliant dans les savons et gommages corporels, pour un effet délicat mais efficace." },
  },
  "urtiga-verde": {
    en: { name: "Green Nettle", origin: "A common wild plant found throughout Europe, traditionally used in infusions and hair care.", properties: "Rich in minerals (iron, silica, potassium) and traditionally associated with strengthening and revitalising the scalp, helping to give hair more body and shine with regular use.", applications: "Used in revitalising hair products, including the oily hair shampoo, where it helps balance the scalp and give hair more body." },
    fr: { name: "Ortie verte", origin: "Une plante sauvage commune dans toute l'Europe, traditionnellement utilisée en infusion et en soins capillaires.", properties: "Riche en minéraux (fer, silice, potassium) et traditionnellement associée au renforcement et à la revitalisation du cuir chevelu, aidant à donner plus de corps et de brillance aux cheveux avec un usage régulier.", applications: "Utilisée dans les produits capillaires revitalisants, y compris le shampoing cheveux gras, où elle aide à équilibrer le cuir chevelu et à donner plus de corps aux cheveux." },
  },
};

export function getIngredientCategoryName(category: string, locale: ProductLocale, fallback: string): string {
  return categoryNames[category]?.[locale] ?? fallback;
}

export function getIngredientCopy(slug: string, locale: ProductLocale, fallback: IngredientCopy): IngredientCopy {
  return copy[slug]?.[locale] ?? fallback;
}
