import { brandSentence } from "@/lib/brand-case";

export type ProductLocale = "pt" | "en" | "fr";

type ProductCopy = { name: string; whyItWorks?: string };

/**
 * English and French copy per product. `whyItWorks` translates the Portuguese
 * "porque funciona" in full — it used to be abridged to a single opening
 * sentence, which left an English or French visitor reading a fraction of what
 * a Portuguese one reads on the same page. A product with no Portuguese copy
 * has no `whyItWorks` here either; there is nothing to translate.
 */
const copy: Record<string, Partial<Record<ProductLocale, ProductCopy>>> = {
  "desodorizante-lavanda-palmarosa": { en: { name: "lavender/palmarosa deodorant", whyItWorks: "shea butter and coconut oil create a creamy, comfortable base, while sodium bicarbonate neutralises odour and corn starch absorbs moisture. on top of that, lavender 40/42 oil calms the skin (helping to avoid irritation) and palmarosa helps control the bacteria and micro-organisms behind bad smells." }, fr: { name: "déodorant lavande/palmarosa", whyItWorks: "le beurre de karité et l'huile de coco créent une base crémeuse et confortable, tandis que le bicarbonate de soude neutralise les odeurs et l'amidon de maïs absorbe l'humidité. en plus de cela, l'huile de lavande 40/42 apaise la peau (en évitant les irritations) et le palmarosa aide à contrôler les bactéries et micro-organismes responsables des mauvaises odeurs." } },
  "desodorizante-tea-tree-erva-principe": { en: { name: "tea tree/lemon verbena deodorant", whyItWorks: "shea butter and coconut oil create a creamy, comfortable base. sodium bicarbonate helps neutralise odour and corn starch helps absorb moisture. tea tree essential oil helps naturally control the bacteria behind bad smells, and lemon verbena adds a fresh, citrusy scent. it is not an antiperspirant: it contains no aluminium and no alcohol, respecting how the skin naturally works instead of blocking perspiration or clogging the pores. if you have an old container, we can reuse it (at a discount) and adapt the formula to what you need: gentler, stronger, or with a different scent." }, fr: { name: "déodorant tea tree/verveine citronnée", whyItWorks: "le beurre de karité et l'huile de coco créent une base crémeuse et confortable. le bicarbonate de soude aide à neutraliser les odeurs et l'amidon de maïs aide à absorber l'humidité. l'huile essentielle de tea tree aide à contrôler naturellement les bactéries responsables des mauvaises odeurs, et la verveine citronnée apporte un parfum frais et citronné. ce n'est pas un déodorant antitranspirant : il ne contient ni aluminium ni alcool, et respecte le fonctionnement naturel de la peau au lieu de bloquer la transpiration ou d'obstruer les pores. si vous avez un ancien contenant, nous pouvons le réutiliser (avec une remise) et adapter la formule à vos besoins : plus doux, plus fort, ou avec un autre parfum." } },
  "champo-oleosos": { en: { name: "solid shampoo for oily hair", whyItWorks: "this shampoo contains no added water: the liquid you see is peppermint hydrosol, which helps give the scalp a feeling of freshness and cleanness. SCI cleanses gently while white clay and flours help purify and balance. we also add nettle and horsetail, dried herbs we grind ourselves, traditionally associated with stronger hair. coconut and argan oils, stearic acid and d-panthenol leave hair nourished and soft without weighing it down, and lemon verbena adds a fresh, invigorating feeling." }, fr: { name: "shampoing solide pour cheveux gras", whyItWorks: "ce shampoing ne contient pas d'eau ajoutée : le liquide que vous voyez est un hydrolat de menthe poivrée, qui aide à donner au cuir chevelu une sensation de fraîcheur et de propreté. le SCI nettoie en douceur tandis que l'argile blanche et les farines aident à purifier et à rééquilibrer. nous ajoutons aussi de l'ortie et de la prêle, des plantes séchées que nous broyons nous-mêmes, traditionnellement associées au renforcement des cheveux. les huiles de coco et d'argan, l'acide stéarique et le d-panthénol laissent les cheveux nourris et doux sans les alourdir, et la verveine citronnée apporte une sensation fraîche et revigorante." } },
  "champo-secos": { en: { name: "solid shampoo for dry hair", whyItWorks: "this is one of our most popular shampoos among people with a sensitive scalp, helping to manage some cases of eczema: the oat and white clay in the formula help calm itching, irritation and flaking of the skin and scalp. SCI cleans without stripping away too much of the natural oils, and the flours help clean gently. coconut oil, shea butter and d-panthenol nourish and help keep dry hair hydrated. lavender hydrosol and lavender 40/42 essential oil add a soft, comforting aromatic profile. because our solid shampoos contain no harsh chemicals, they can also be used on the body as a soap (this one in particular has been used by people with atopic skin)." }, fr: { name: "shampoing solide pour cheveux secs", whyItWorks: "c'est l'un de nos shampoings les plus recherchés par les personnes au cuir chevelu sensible, et il aide à gérer certains cas d'eczéma : l'avoine et l'argile blanche de la formule aident à apaiser les démangeaisons, les irritations et les squames de la peau et du cuir chevelu. le SCI nettoie sans retirer à l'excès les huiles naturelles, et les farines aident à nettoyer en douceur. l'huile de coco, le beurre de karité et le d-panthénol nourrissent et aident à maintenir l'hydratation des cheveux secs. l'hydrolat de lavande et l'huile essentielle de lavande 40/42 apportent un profil aromatique doux et réconfortant. comme nos shampoings solides ne contiennent pas de produits chimiques agressifs, ils peuvent aussi être utilisés sur le corps comme savon (celui-ci en particulier est utilisé par des personnes à la peau atopique)." } },
  "champos-para-cabelos-normais": { en: { name: "solid shampoo for normal hair", whyItWorks: "the formula combines gentle cleansing from SCI with the balancing action of white clay, flours and lavender hydrosol. coconut oil, argan oil and d-panthenol help keep normal hair soft and hydrated, while stearic acid gives the bar body without making the wash harsh." }, fr: { name: "shampoing solide pour cheveux normaux", whyItWorks: "la formule associe le nettoyage doux du SCI à l'action équilibrante de l'argile blanche, des farines et de l'hydrolat de lavande. l'huile de coco, l'huile d'argan et le d-panthénol aident à garder les cheveux normaux doux et hydratés, tandis que l'acide stéarique donne du corps au pain sans rendre le lavage agressif." } },
  "champo-neutro-para-criancas": { en: { name: "gentle solid shampoo for children", whyItWorks: "SCI provides gentle cleansing, while white clay and flours help clean without irritating. coconut oil, shea butter and d-panthenol leave hair soft and comfortable, and roman chamomile hydrosol adds a calming touch to the formula. stearic acid gives the bar its consistency." }, fr: { name: "shampoing solide doux pour enfants", whyItWorks: "le SCI nettoie en douceur, tandis que l'argile blanche et les farines aident à nettoyer sans agresser. l'huile de coco, le beurre de karité et le d-panthénol laissent les cheveux doux et confortables, et l'hydrolat de camomille romaine apporte une touche apaisante à la formule. l'acide stéarique donne sa consistance au pain." } },
  "champo-queda": { en: { name: "solid shampoo for hair loss" }, fr: { name: "shampoing solide pour la chute de cheveux" } },
  "amaciador": { en: { name: "conditioner", whyItWorks: "BTMS and cetyl alcohol condition and detangle hair, leaving it softer and easier to comb. shea butter and sweet almond and argan oils nourish the lengths and help reduce the feeling of dryness. vitamin E protects the oil phase from oxidation, while lavender adds a soft scent." }, fr: { name: "après-shampoing", whyItWorks: "le BTMS et l'alcool cétylique conditionnent et démêlent les cheveux, les laissant plus doux et plus faciles à coiffer. le beurre de karité et les huiles d'amande douce et d'argan nourrissent les longueurs et aident à réduire la sensation de sécheresse. la vitamine E protège la phase huileuse de l'oxydation, tandis que la lavande apporte un parfum doux." } },
  "mascara-150ml": { en: { name: "150 ml hair mask", whyItWorks: "BTMS conditions and helps detangle hair, while coconut oil leaves strands softer. water keeps the formula light; rosemary QT cineole and lemon add a fresh, invigorating scent. cosgard helps protect the water-based formula." }, fr: { name: "masque capillaire 150 ml", whyItWorks: "le BTMS conditionne et aide à démêler les cheveux, tandis que l'huile de coco laisse les fibres plus douces. l'eau allège la formule ; le romarin QT cinéole et le citron apportent un parfum frais et revigorant. le cosgard aide à protéger la formule à base d'eau." } },
  // named for what it is for, not for what it weighs — the slug moved with it
  "sabonete-de-rosto": { en: { name: "face soap", whyItWorks: "aloe vera is what hydrates deepest, and ours is organic, harvested fresh at home. vegetable glycerine helps the skin hold on to that hydration instead of losing it through the day. lavender essential oil helps calm the skin and carries the scent, with bergamot adding a fresher citrus note. and the poppy seeds exfoliate gently: they are round and all the same size, so they clean without scratching, even somewhere as sensitive as the face." }, fr: { name: "savon pour le visage", whyItWorks: "l'aloe vera est ce qui hydrate le plus en profondeur, et le nôtre est biologique, cueilli frais à la maison. la glycérine végétale aide la peau à retenir cette hydratation au lieu de la perdre au fil de la journée. l'huile essentielle de lavande aide à apaiser la peau et apporte le parfum, la bergamote y ajoutant une note d'agrumes plus fraîche. et les graines de pavot exfolient délicatement : elles sont rondes et toutes de la même taille, elles nettoient donc sans rayer, même sur une zone aussi sensible que le visage." } },
  "sabonete-de-corpo": { en: { name: "body soap", whyItWorks: "it is the same soap we make for the face, in a larger bar, so it lasts longer on the body. aloe vera is what hydrates deepest, and ours is organic, harvested fresh at home. vegetable glycerine helps the skin hold on to that hydration instead of losing it through the day. lavender essential oil helps calm the skin and carries the scent, with bergamot adding a fresher citrus note. and the poppy seeds exfoliate gently: they are round and all the same size, so they clean without scratching." }, fr: { name: "savon pour le corps", whyItWorks: "c'est le même savon que nous faisons pour le visage, en pain plus grand, pour qu'il dure plus longtemps sur le corps. l'aloe vera est ce qui hydrate le plus en profondeur, et le nôtre est biologique, cueilli frais à la maison. la glycérine végétale aide la peau à retenir cette hydratation au lieu de la perdre au fil de la journée. l'huile essentielle de lavande aide à apaiser la peau et apporte le parfum, la bergamote y ajoutant une note d'agrumes plus fraîche. et les graines de pavot exfolient délicatement : elles sont rondes et toutes de la même taille, elles nettoient donc sans rayer." } },
  "vela-citronela": { en: { name: "citronella candle" }, fr: { name: "bougie à la citronnelle" } },
  "vela-massagem": { en: { name: "massage candle", whyItWorks: "this one is made to go on the skin. soy wax melts at a much lower temperature than the paraffin in supermarket candles, and that is what lets the melted wax be poured straight onto the skin for a massage without burning. being a plant wax, it moisturises the skin as it is spread, and leaves none of the sticky film on top that the others do." }, fr: { name: "bougie de massage", whyItWorks: "celle-ci est faite pour la peau. la cire de soja fond à une température bien plus basse que la paraffine des bougies de supermarché, et c'est ce qui permet de verser la cire fondue directement sur la peau pour un massage, sans brûler. étant une cire végétale, elle hydrate la peau à mesure qu'on l'étale, et ne laisse pas dessus ce film collant que les autres laissent." } },
  "vela-decorada": { en: { name: "decorated candle" }, fr: { name: "bougie décorée" } },
  "vela-colorida": { en: { name: "coloured candle" }, fr: { name: "bougie colorée" } },
  "vela-com-mensagem": { en: { name: "candle with a message", whyItWorks: "we can write your message on the candle: a name, a date, a dedication, a line only you understand. we have made candles for birthdays, mother's day and father's day, christenings and invitations to godmothers and godfathers, weddings, valentine's day, thank yous, farewells and new year's eve. tell us what it should say and we build the candle around that message (it works with any of our candles). each one is made after you talk to us, so please ask a little ahead of time. and if you have a jar, a mug or a bowl you would like us to use, just bring us the container." }, fr: { name: "bougie avec message", whyItWorks: "nous pouvons écrire votre message sur la bougie : un prénom, une date, une dédicace, une phrase que vous seuls comprenez. nous avons déjà fait des bougies pour des anniversaires, la fête des mères et la fête des pères, des baptêmes et des demandes à des marraines et parrains, des mariages, la saint-valentin, des remerciements, des adieux et des réveillons. dites-nous ce qui doit y figurer et nous fabriquons la bougie autour de ce message (cela fonctionne avec n'importe laquelle de nos bougies). chacune est fabriquée après votre message, pensez donc à demander un peu à l'avance. et si vous avez un bocal, une tasse ou un bol que vous aimeriez utiliser, apportez-nous simplement le récipient." } },
  "roll-on-relaxamento": { en: { name: "relaxation roll-on" }, fr: { name: "roll-on relaxation" } },
  "roll-on-cabeca": { en: { name: "head roll-on" }, fr: { name: "roll-on tête" } },
  "roll-on-sinusite": { en: { name: "sinus roll-on", whyItWorks: "sweet almond oil provides a gentle base for applying the blend to the skin. peppermint and eucalyptus radiata add a cool feeling and help create an aroma that supports the sense of clearer breathing, while tea tree reinforces the formula's purifying profile." }, fr: { name: "roll-on sinus", whyItWorks: "l'huile d'amande douce offre une base douce pour appliquer le mélange sur la peau. la menthe poivrée et l'eucalyptus radiata apportent une sensation de fraîcheur et aident à créer un arôme qui favorise la sensation de respiration dégagée, tandis que le tea tree renforce le profil purifiant de la formule." } },
  "spray-relaxante": { en: { name: "relaxing spray", whyItWorks: "it works both ways: spray it into the air, on the pillow or on the bedlinen, and on the skin too, as a perfume. the essential oils do the work. lavender is the most recognisable floral, herbaceous scent of all the ones we use, traditionally associated with a feeling of rest, and roman chamomile adds a sweet, softened note, the kind associated with a calm moment at the end of the day. the 96% alcohol is what lets those oils mix with water at all (something water alone cannot do), and it is why the spray does not separate into two layers; because it evaporates quickly, it does not leave the surface wet either. distilled water, with no minerals or residue, keeps the formula clean for longer and leaves no marks where the spray settles. the lavender flowers float whole in the bottle, releasing their scent slowly." }, fr: { name: "spray relaxant", whyItWorks: "il sert aux deux usages : vaporisez-le dans l'air, sur l'oreiller ou sur les draps, et aussi sur la peau, comme un parfum. ce sont les huiles essentielles qui font le travail. la lavande est le parfum floral et herbacé le plus reconnaissable de tous ceux que nous utilisons, traditionnellement associé à une sensation de repos, et la camomille romaine y ajoute une note douce et adoucie, de celles que l'on associe à un moment de calme en fin de journée. l'alcool à 96° est ce qui permet à ces huiles de se mélanger réellement à l'eau (ce que l'eau seule ne fait pas), et c'est pourquoi le spray ne se sépare pas en deux couches ; comme il s'évapore vite, il ne laisse pas non plus la surface mouillée. l'eau distillée, sans minéraux ni résidus, garde la formule propre plus longtemps et ne laisse pas de marques là où le spray se dépose. les fleurs de lavande flottent entières dans le flacon et libèrent leur parfum peu à peu." } },
  "sais-de-banho-relaxante": { en: { name: "relaxing bath salts", whyItWorks: "made with 100% natural sea salt, straight from the salt pans and untreated, with essential oils and dried flowers. truly lucrescente, for a soak in the bath or a deeply relaxing, invigorating foot bath." }, fr: { name: "sels de bain relaxants", whyItWorks: "préparés avec du sel marin 100 % naturel, venu directement des salines et sans aucun traitement, avec des huiles essentielles et des fleurs séchées. vraiment lucrescents, pour un bain d'immersion ou un bain de pieds bien relaxant et revigorant." } },
  "batom-tijolo": { en: { name: "brick lip balm" }, fr: { name: "baume à lèvres brique" } },
  "batom-herpes": { en: { name: "cold sore balm" }, fr: { name: "baume boutons de fièvre" } },
  "batom-laranja": { en: { name: "orange lip balm", whyItWorks: "beeswax and soy wax give the balm its consistency and help protect the lips. cocoa butter and sweet almond oil nourish and soften, while sweet orange essential oil adds a sweet, bright citrus scent." }, fr: { name: "baume à lèvres orange", whyItWorks: "la cire d'abeille et la cire de soja donnent sa consistance au baume et aident à protéger les lèvres. le beurre de cacao et l'huile d'amande douce nourrissent et adoucissent, tandis que l'huile essentielle d'orange douce apporte un parfum d'agrumes doux et lumineux." } },
  "batom-natural": { en: { name: "natural lip balm", whyItWorks: "beeswax and soy wax give the balm its consistency and help create a protective layer on the lips. cocoa butter and sweet almond oil nourish and soften, leaving the lips comfortable without a heavy feel." }, fr: { name: "baume à lèvres naturel", whyItWorks: "la cire d'abeille et la cire de soja donnent sa consistance au baume et aident à créer une couche protectrice sur les lèvres. le beurre de cacao et l'huile d'amande douce nourrissent et adoucissent, laissant les lèvres confortables sans sensation de lourdeur." } },
  "batom-h-pimenta": { en: { name: "peppermint lip balm", whyItWorks: "beeswax and soy wax give the balm its consistency and help protect the lips. cocoa butter and sweet almond oil nourish and soften, while peppermint essential oil adds a cool, refreshing feeling." }, fr: { name: "baume à lèvres menthe poivrée", whyItWorks: "la cire d'abeille et la cire de soja donnent sa consistance au baume et aident à protéger les lèvres. le beurre de cacao et l'huile d'amande douce nourrissent et adoucissent, tandis que l'huile essentielle de menthe poivrée apporte une sensation fraîche et rafraîchissante." } },
  inalador: { en: { name: "inhaler", whyItWorks: "the combination of peppermint, eucalyptus radiata and ravintsara creates a fresh, penetrating aroma associated with a feeling of clearer breathing. lavender 40/42 and roman chamomile balance the blend with softer, more comforting notes." }, fr: { name: "inhalateur", whyItWorks: "la combinaison de menthe poivrée, d'eucalyptus radiata et de ravintsara crée un arôme frais et pénétrant, associé à une sensation de respiration dégagée. la lavande 40/42 et la camomille romaine équilibrent le mélange avec des notes plus douces et réconfortantes." } },
  ambientador: { en: { name: "soy wax air freshener" }, fr: { name: "désodorisant à la cire de soja" } },
};

export function getProductCopy(slug: string, locale: ProductLocale, fallback: ProductCopy): ProductCopy {
  const entry = copy[slug]?.[locale] ?? fallback;
  // The names are already lowercase here, and so is "porque funciona" today —
  // but it is written in Supabase, so it is put into the brand's lowercase for
  // the same reason the ingredient copy is. SCI and BTMS survive.
  return { name: entry.name, whyItWorks: entry.whyItWorks ? brandSentence(entry.whyItWorks) : undefined };
}
