import { brandSentence } from "@/lib/brand-case";

export type ProductLocale = "pt" | "en" | "fr";

type ProductCopy = { name: string; whyItWorks?: string };

const copy: Record<string, Partial<Record<ProductLocale, ProductCopy>>> = {
  "desodorizante-lavanda-palmarosa": { en: { name: "lavender/palmarosa deodorant", whyItWorks: "shea butter and coconut oil create a comfortable base. baking soda helps neutralise odour and corn starch helps absorb moisture. lavender and palmarosa essential oils add a soft floral scent." }, fr: { name: "déodorant lavande/palmarosa", whyItWorks: "le beurre de karité et l'huile de coco créent une base confortable. le bicarbonate de soude aide à neutraliser les odeurs et l'amidon de maïs aide à absorber l'humidité. les huiles essentielles de lavande et de palmarosa apportent un parfum floral doux." } },
  "desodorizante-tea-tree-erva-principe": { en: { name: "tea tree/lemon verbena deodorant", whyItWorks: "shea butter and coconut oil create a comfortable base. baking soda helps neutralise odour and corn starch helps absorb moisture. tea tree essential oil helps naturally control odour-causing bacteria, while lemon verbena adds a fresh, citrusy note." }, fr: { name: "déodorant tea tree/verveine citronnée", whyItWorks: "le beurre de karité et l'huile de coco créent une base confortable. le bicarbonate de soude aide à neutraliser les odeurs et l'amidon de maïs aide à absorber l'humidité. l'huile essentielle de tea tree aide à contrôler naturellement les bactéries responsables des mauvaises odeurs, tandis que la verveine citronnée apporte une note fraîche et citronnée." } },
  "champo-oleosos": { en: { name: "solid shampoo for oily hair", whyItWorks: "this shampoo contains no added water — the liquid is peppermint hydrosol, which helps create a feeling of freshness." }, fr: { name: "shampoing solide pour cheveux gras", whyItWorks: "ce shampoing ne contient pas d'eau ajoutée — le liquide est un hydrolat de menthe poivrée, qui apporte une sensation de fraîcheur." } },
  "champo-secos": { en: { name: "solid shampoo for dry hair", whyItWorks: "one of our most popular shampoos for sensitive scalps, helping to manage some cases of eczema: oat and clay help soothe the skin." }, fr: { name: "shampoing solide pour cheveux secs", whyItWorks: "l'un de nos shampoings les plus appréciés pour les cuirs chevelus sensibles, qui aide à apaiser certains cas d'eczéma : l'avoine et l'argile prennent soin de la peau." } },
  "champos-para-cabelos-normais": { en: { name: "solid shampoo for normal hair", whyItWorks: "the formula combines gentle cleansing from SCI with the balancing action of white clay, flours and lavender hydrosol." }, fr: { name: "shampoing solide pour cheveux normaux", whyItWorks: "la formule associe le nettoyage doux du SCI à l'action équilibrante de l'argile blanche, des farines et de l'hydrolat de lavande." } },
  "champo-neutro-para-criancas": { en: { name: "gentle shampoo for children", whyItWorks: "SCI provides gentle cleansing, while white clay and flours help clean without irritating." }, fr: { name: "shampoing doux pour enfants", whyItWorks: "le SCI nettoie en douceur, tandis que l'argile blanche et les farines aident à nettoyer sans agresser." } },
  "champo-queda": { en: { name: "hair-loss shampoo" }, fr: { name: "shampoing anti-chute" } },
  "amaciador": { en: { name: "conditioner", whyItWorks: "BTMS and cetyl alcohol condition and detangle hair, leaving it softer and easier to comb, while shea butter and sweet almond, argan and avocado oils add extra nourishment." }, fr: { name: "après-shampoing", whyItWorks: "le BTMS et l'alcool cétylique conditionnent et démêlent les cheveux, les laissant plus doux et faciles à coiffer, tandis que le beurre de karité et les huiles d'amande douce, d'argan et d'avocat apportent une nutrition supplémentaire." } },
  "mascara-150ml": { en: { name: "150 ml hair mask", whyItWorks: "BTMS conditions and helps detangle hair, while coconut oil leaves strands softer. rosemary CT cineole helps strengthen hair and support growth, and lemon's antioxidants help promote shine." }, fr: { name: "masque capillaire 150 ml", whyItWorks: "le BTMS conditionne et aide à démêler les cheveux, tandis que l'huile de coco les laisse plus doux. le romarin CT cinéole aide à renforcer les cheveux et à soutenir leur pousse, et les antioxydants du citron aident à faire briller les cheveux." } },
  "sabonete-corpo-aveia": { en: { name: "oat body soap" }, fr: { name: "savon pour le corps à l'avoine" } },
  "sabonete-40g": { en: { name: "40 g soap" }, fr: { name: "savon 40 g" } },
  "sabonete-grande": { en: { name: "large soap" }, fr: { name: "grand savon" } },
  "vela-citronela": { en: { name: "citronella candle", whyItWorks: "lucrescente candles are made with soy wax, which melts slowly and evenly: this means they last longer, with no wasted wax, and contain no petroleum derivatives or synthetic fragrances. most of the decorative elements we use are natural: dried flowers and leaves, shells, pebbles... some plant materials are even pressed and prepared by us. if you prefer, we can make your candles in your own jars, mugs or cups — just give us the containers." }, fr: { name: "bougie à la citronnelle", whyItWorks: "les bougies lucrescente sont faites avec de la cire de soja, qui fond lentement et uniformément : cela signifie qu'elles durent plus longtemps, sans gaspillage de cire, et ne contiennent pas de dérivés du pétrole ni de parfums synthétiques. la plupart des éléments décoratifs que nous utilisons sont naturels : fleurs et feuilles séchées, coquillages, petites pierres... certains éléments végétaux sont même pressés et préparés par nous. si tu préfères, nous pouvons faire tes bougies dans tes propres bocaux, tasses ou coupes — tu dois juste nous donner les récipients." } },
  "vela-massagem": { en: { name: "massage candle", whyItWorks: "lucrescente candles are made with soy wax, which melts slowly and evenly: this means they last longer, with no wasted wax, and contain no petroleum derivatives or synthetic fragrances. most of the decorative elements we use are natural: dried flowers and leaves, shells, pebbles... some plant materials are even pressed and prepared by us. if you prefer, we can make your candles in your own jars, mugs or cups — just give us the containers." }, fr: { name: "bougie de massage", whyItWorks: "les bougies lucrescente sont faites avec de la cire de soja, qui fond lentement et uniformément : cela signifie qu'elles durent plus longtemps, sans gaspillage de cire, et ne contiennent pas de dérivés du pétrole ni de parfums synthétiques. la plupart des éléments décoratifs que nous utilisons sont naturels : fleurs et feuilles séchées, coquillages, petites pierres... certains éléments végétaux sont même pressés et préparés par nous. si tu préfères, nous pouvons faire tes bougies dans tes propres bocaux, tasses ou coupes — tu dois juste nous donner les récipients." } },
  "vela-decorada": { en: { name: "decorated candle", whyItWorks: "lucrescente candles are made with soy wax, which melts slowly and evenly: this means they last longer, with no wasted wax, and contain no petroleum derivatives or synthetic fragrances. most of the decorative elements we use are natural: dried flowers and leaves, shells, pebbles... some plant materials are even pressed and prepared by us. if you prefer, we can make your candles in your own jars, mugs or cups — just give us the containers." }, fr: { name: "bougie décorée", whyItWorks: "les bougies lucrescente sont faites avec de la cire de soja, qui fond lentement et uniformément : cela signifie qu'elles durent plus longtemps, sans gaspillage de cire, et ne contiennent pas de dérivés du pétrole ni de parfums synthétiques. la plupart des éléments décoratifs que nous utilisons sont naturels : fleurs et feuilles séchées, coquillages, petites pierres... certains éléments végétaux sont même pressés et préparés par nous. si tu préfères, nous pouvons faire tes bougies dans tes propres bocaux, tasses ou coupes — tu dois juste nous donner les récipients." } },
  "vela-colorida": { en: { name: "coloured candle", whyItWorks: "lucrescente candles are made with soy wax, which melts slowly and evenly: this means they last longer, with no wasted wax, and contain no petroleum derivatives or synthetic fragrances. most of the decorative elements we use are natural: dried flowers and leaves, shells, pebbles... some plant materials are even pressed and prepared by us. if you prefer, we can make your candles in your own jars, mugs or cups — just give us the containers." }, fr: { name: "bougie colorée", whyItWorks: "les bougies lucrescente sont faites avec de la cire de soja, qui fond lentement et uniformément : cela signifie qu'elles durent plus longtemps, sans gaspillage de cire, et ne contiennent pas de dérivés du pétrole ni de parfums synthétiques. la plupart des éléments décoratifs que nous utilisons sont naturels : fleurs et feuilles séchées, coquillages, petites pierres... certains éléments végétaux sont même pressés et préparés par nous. si tu préfères, nous pouvons faire tes bougies dans tes propres bocaux, tasses ou coupes — tu dois juste nous donner les récipients." } },
  "roll-on-relaxamento": { en: { name: "relaxation roll-on" }, fr: { name: "roll-on relaxation" } },
  "roll-on-cabeca": { en: { name: "head roll-on" }, fr: { name: "roll-on tête" } },
  "roll-on-sinusite": { en: { name: "sinus roll-on", whyItWorks: "sweet almond oil provides a gentle base for applying the blend to the skin." }, fr: { name: "roll-on sinus", whyItWorks: "l'huile d'amande douce offre une base douce pour appliquer le mélange sur la peau." } },
  "spray-relaxante": { en: { name: "relaxing spray" }, fr: { name: "spray relaxant" } },
  "sais-de-banho-relaxante": { en: { name: "relaxing bath salts", whyItWorks: "made with 100% natural sea salt, straight from the salt pans and untreated, with essential oils and dried flowers." }, fr: { name: "sels de bain relaxants", whyItWorks: "préparés avec du sel marin 100 % naturel, directement issu des salines et sans traitement, des huiles essentielles et des fleurs séchées." } },
  "batom-tijolo": { en: { name: "brick lip balm" }, fr: { name: "baume à lèvres brique" } },
  "batom-herpes": { en: { name: "cold sore balm" }, fr: { name: "baume boutons de fièvre" } },
  "batom-laranja": { en: { name: "orange lip balm", whyItWorks: "beeswax and soy wax give the balm its consistency and help protect the lips." }, fr: { name: "baume à lèvres orange", whyItWorks: "la cire d'abeille et la cire de soja donnent sa consistance au baume et aident à protéger les lèvres." } },
  "batom-natural": { en: { name: "natural lip balm", whyItWorks: "beeswax and soy wax give the balm its consistency and help create a protective layer on the lips." }, fr: { name: "baume à lèvres naturel", whyItWorks: "la cire d'abeille et la cire de soja donnent sa consistance au baume et aident à créer une couche protectrice sur les lèvres." } },
  "batom-h-pimenta": { en: { name: "peppermint lip balm", whyItWorks: "beeswax and soy wax give the balm its consistency and help protect the lips." }, fr: { name: "baume à lèvres menthe poivrée", whyItWorks: "la cire d'abeille et la cire de soja donnent sa consistance au baume et aident à protéger les lèvres." } },
  inalador: { en: { name: "inhaler", whyItWorks: "peppermint, eucalyptus radiata and ravintsara create a fresh, penetrating aroma associated with a feeling of clearer breathing." }, fr: { name: "inhalateur", whyItWorks: "la menthe poivrée, l'eucalyptus radiata et le ravintsara créent un arôme frais et pénétrant, associé à une sensation de respiration plus libre." } },
  ambientador: { en: { name: "soy wax air freshener" }, fr: { name: "désodorisant à la cire de soja" } },
};

export function getProductCopy(slug: string, locale: ProductLocale, fallback: ProductCopy): ProductCopy {
  const entry = copy[slug]?.[locale] ?? fallback;
  // The names are already lowercase here, and so is "porque funciona" today —
  // but it is written in Supabase, so it is put into the brand's lowercase for
  // the same reason the ingredient copy is. SCI and BTMS survive.
  return { name: entry.name, whyItWorks: entry.whyItWorks ? brandSentence(entry.whyItWorks) : undefined };
}
