import raw from "@/data/editorial.json";

export type EditorialImage = { path: string; alt: string } | null;
export type EditorialKey = "home-hero" | "sobre" | "cuidados-reuse" | "cuidados-velas" | "cuidados-solidos";

type Shape = Record<EditorialKey, EditorialImage> & { categories: Record<string, { file: string; alt: string } | null> };

/** Editorial photos (real, curated from the supplied set). Generated by `npm run images`. */
export const editorial = raw as unknown as Shape;
